<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Data Management - Cross-Sectional Data | LBOMETR Course Book</title>
  <meta name="description" content="An introduction to the LBOMETR Course Book." />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Data Management - Cross-Sectional Data | LBOMETR Course Book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An introduction to the LBOMETR Course Book." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Data Management - Cross-Sectional Data | LBOMETR Course Book" />
  
  <meta name="twitter:description" content="An introduction to the LBOMETR Course Book." />
  

<meta name="author" content="Jem Marie M. Nario" />


<meta name="date" content="2025-06-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="basic-introduction-to-r.html"/>
<link rel="next" href="data-management---time-series-and-panel-data.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<h1>LBOMETR Course Book</h1>
<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#about-me"><i class="fa fa-check"></i><b>1.1</b> About Me</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i><b>2</b> Syllabus</a>
<ul>
<li class="chapter" data-level="2.1" data-path="syllabus.html"><a href="syllabus.html#course-information"><i class="fa fa-check"></i><b>2.1</b> Course Information</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="syllabus.html"><a href="syllabus.html#general-course-description"><i class="fa fa-check"></i><b>2.1.1</b> General Course Description</a></li>
<li class="chapter" data-level="2.1.2" data-path="syllabus.html"><a href="syllabus.html#specific-course-description"><i class="fa fa-check"></i><b>2.1.2</b> Specific Course Description</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="syllabus.html"><a href="syllabus.html#learning-goals-and-outcomes"><i class="fa fa-check"></i><b>2.2</b> Learning Goals and Outcomes</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="syllabus.html"><a href="syllabus.html#expected-lasallian-graduate-attributes-elgas"><i class="fa fa-check"></i><b>2.2.1</b> Expected Lasallian Graduate Attributes (ELGAs)</a></li>
<li class="chapter" data-level="2.2.2" data-path="syllabus.html"><a href="syllabus.html#programme-learning-outcomes-plos"><i class="fa fa-check"></i><b>2.2.2</b> Programme Learning Outcomes (PLOs)</a></li>
<li class="chapter" data-level="2.2.3" data-path="syllabus.html"><a href="syllabus.html#course-learning-outcomes-clos"><i class="fa fa-check"></i><b>2.2.3</b> Course Learning Outcomes (CLOs)</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="syllabus.html"><a href="syllabus.html#mapping-of-clos-to-elgas"><i class="fa fa-check"></i><b>2.3</b> Mapping of CLOs to ELGAs</a></li>
<li class="chapter" data-level="2.4" data-path="syllabus.html"><a href="syllabus.html#mapping-of-clos-to-plos"><i class="fa fa-check"></i><b>2.4</b> Mapping of CLOs to PLOs</a></li>
<li class="chapter" data-level="2.5" data-path="syllabus.html"><a href="syllabus.html#course-assessments"><i class="fa fa-check"></i><b>2.5</b> Course Assessments</a></li>
<li class="chapter" data-level="2.6" data-path="syllabus.html"><a href="syllabus.html#grading-system"><i class="fa fa-check"></i><b>2.6</b> Grading System</a></li>
<li class="chapter" data-level="2.7" data-path="syllabus.html"><a href="syllabus.html#class-policies"><i class="fa fa-check"></i><b>2.7</b> Class Policies</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="syllabus.html"><a href="syllabus.html#attendance"><i class="fa fa-check"></i><b>2.7.1</b> 1. Attendance</a></li>
<li class="chapter" data-level="2.7.2" data-path="syllabus.html"><a href="syllabus.html#course-materials"><i class="fa fa-check"></i><b>2.7.2</b> 2. Course Materials</a></li>
<li class="chapter" data-level="2.7.3" data-path="syllabus.html"><a href="syllabus.html#grading-notes"><i class="fa fa-check"></i><b>2.7.3</b> 3. Grading Notes</a></li>
<li class="chapter" data-level="2.7.4" data-path="syllabus.html"><a href="syllabus.html#incentives-and-extra-credit"><i class="fa fa-check"></i><b>2.7.4</b> 4. Incentives and Extra Credit</a></li>
<li class="chapter" data-level="2.7.5" data-path="syllabus.html"><a href="syllabus.html#computer-practicals"><i class="fa fa-check"></i><b>2.7.5</b> 5. Computer Practicals</a></li>
<li class="chapter" data-level="2.7.6" data-path="syllabus.html"><a href="syllabus.html#groupings-and-peer-evaluation"><i class="fa fa-check"></i><b>2.7.6</b> 6. Groupings and Peer Evaluation</a></li>
<li class="chapter" data-level="2.7.7" data-path="syllabus.html"><a href="syllabus.html#extensions"><i class="fa fa-check"></i><b>2.7.7</b> 7. Extensions</a></li>
<li class="chapter" data-level="2.7.8" data-path="syllabus.html"><a href="syllabus.html#use-of-ai-tools"><i class="fa fa-check"></i><b>2.7.8</b> 8. Use of AI Tools</a></li>
<li class="chapter" data-level="2.7.9" data-path="syllabus.html"><a href="syllabus.html#consultations"><i class="fa fa-check"></i><b>2.7.9</b> 9. Consultations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="course-assessments-1.html"><a href="course-assessments-1.html"><i class="fa fa-check"></i><b>3</b> Course Assessments</a>
<ul>
<li class="chapter" data-level="3.1" data-path="course-assessments-1.html"><a href="course-assessments-1.html#data-story-archive"><i class="fa fa-check"></i><b>3.1</b> Data Story Archive</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="course-assessments-1.html"><a href="course-assessments-1.html#requirements"><i class="fa fa-check"></i><b>3.1.1</b> Requirements</a></li>
<li class="chapter" data-level="3.1.2" data-path="course-assessments-1.html"><a href="course-assessments-1.html#submission"><i class="fa fa-check"></i><b>3.1.2</b> Submission</a></li>
<li class="chapter" data-level="3.1.3" data-path="course-assessments-1.html"><a href="course-assessments-1.html#grading-rubric-for-data-story-archive"><i class="fa fa-check"></i><b>3.1.3</b> Grading Rubric for Data Story Archive</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="course-assessments-1.html"><a href="course-assessments-1.html#data-story-presentation"><i class="fa fa-check"></i><b>3.2</b> Data Story Presentation</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="course-assessments-1.html"><a href="course-assessments-1.html#requirements-1"><i class="fa fa-check"></i><b>3.2.1</b> Requirements</a></li>
<li class="chapter" data-level="3.2.2" data-path="course-assessments-1.html"><a href="course-assessments-1.html#grading-rubric"><i class="fa fa-check"></i><b>3.2.2</b> Grading Rubric</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="grouping-process.html"><a href="grouping-process.html"><i class="fa fa-check"></i><b>4</b> Grouping Process</a>
<ul>
<li class="chapter" data-level="4.1" data-path="grouping-process.html"><a href="grouping-process.html#how-groups-are-formed"><i class="fa fa-check"></i><b>4.1</b> How Groups Are Formed</a></li>
<li class="chapter" data-level="4.2" data-path="grouping-process.html"><a href="grouping-process.html#announcement-of-groups"><i class="fa fa-check"></i><b>4.2</b> Announcement of Groups</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-story-research-question.html"><a href="data-story-research-question.html"><i class="fa fa-check"></i><b>5</b> Data Story Research Question</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-story-research-question.html"><a href="data-story-research-question.html#guidelines-in-conducting-data-story"><i class="fa fa-check"></i><b>5.1</b> Guidelines in Conducting Data Story</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="data-story-research-question.html"><a href="data-story-research-question.html#research-question"><i class="fa fa-check"></i><b>5.1.1</b> Research Question:</a></li>
<li class="chapter" data-level="5.1.2" data-path="data-story-research-question.html"><a href="data-story-research-question.html#relevance"><i class="fa fa-check"></i><b>5.1.2</b> Relevance</a></li>
<li class="chapter" data-level="5.1.3" data-path="data-story-research-question.html"><a href="data-story-research-question.html#for-the-data-story-should-i-use-kaggle"><i class="fa fa-check"></i><b>5.1.3</b> For the data story, should I use Kaggle?</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="data-story-research-question.html"><a href="data-story-research-question.html#comments-on-research-questions"><i class="fa fa-check"></i><b>5.2</b> Comments on Research Questions:</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html"><i class="fa fa-check"></i><b>6</b> Basic Introduction to R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#session-information"><i class="fa fa-check"></i><b>6.1</b> Session Information</a></li>
<li class="chapter" data-level="6.2" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#preliminaries"><i class="fa fa-check"></i><b>6.2</b> Preliminaries</a></li>
<li class="chapter" data-level="6.3" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#quarto-markdown"><i class="fa fa-check"></i><b>6.3</b> Quarto Markdown</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#starting-a-quarto-file"><i class="fa fa-check"></i><b>6.3.1</b> 1. Starting a Quarto File</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#packages"><i class="fa fa-check"></i><b>6.4</b> Packages</a></li>
<li class="chapter" data-level="6.5" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#instructions-for-managing-working-directories"><i class="fa fa-check"></i><b>6.5</b> Instructions for Managing Working Directories</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#local-working-directory-setup"><i class="fa fa-check"></i><b>6.5.1</b> 1. Local Working Directory Setup</a></li>
<li class="chapter" data-level="6.5.2" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#file-naming-convention"><i class="fa fa-check"></i><b>6.5.2</b> 2. File Naming Convention</a></li>
<li class="chapter" data-level="6.5.3" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#shared-google-drive-setup"><i class="fa fa-check"></i><b>6.5.3</b> 3. Shared Google Drive Setup</a></li>
<li class="chapter" data-level="6.5.4" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#workflow-for-.qmd-files"><i class="fa fa-check"></i><b>6.5.4</b> 4. Workflow for <code>.qmd</code> files</a></li>
<li class="chapter" data-level="6.5.5" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#rendering-the-final-report"><i class="fa fa-check"></i><b>6.5.5</b> 5. Rendering the Final Report</a></li>
<li class="chapter" data-level="6.5.6" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#summary-workflow"><i class="fa fa-check"></i><b>6.5.6</b> Summary Workflow</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#note"><i class="fa fa-check"></i><b>6.6</b> Note:</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html"><i class="fa fa-check"></i><b>7</b> Data Management - Cross-Sectional Data</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#where-to-get-data"><i class="fa fa-check"></i><b>7.1</b> Where to Get Data?</a></li>
<li class="chapter" data-level="7.2" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#preliminaries-1"><i class="fa fa-check"></i><b>7.2</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#dataset"><i class="fa fa-check"></i><b>7.2.1</b> Dataset</a></li>
<li class="chapter" data-level="7.2.2" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#packages-1"><i class="fa fa-check"></i><b>7.2.2</b> Packages</a></li>
<li class="chapter" data-level="7.2.3" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#setting-up-the-directory"><i class="fa fa-check"></i><b>7.2.3</b> Setting up the Directory</a></li>
<li class="chapter" data-level="7.2.4" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#clean-everything"><i class="fa fa-check"></i><b>7.2.4</b> Clean Everything</a></li>
<li class="chapter" data-level="7.2.5" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#importing-the-dataset"><i class="fa fa-check"></i><b>7.2.5</b> Importing the Dataset</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#data-cleaning"><i class="fa fa-check"></i><b>7.3</b> Data Cleaning</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#renaming-the-variables"><i class="fa fa-check"></i><b>7.3.1</b> Renaming the Variables</a></li>
<li class="chapter" data-level="7.3.2" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#sorting-certain-values"><i class="fa fa-check"></i><b>7.3.2</b> Sorting certain values</a></li>
<li class="chapter" data-level="7.3.3" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#pipe-operator"><i class="fa fa-check"></i><b>7.3.3</b> Pipe Operator</a></li>
<li class="chapter" data-level="7.3.4" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#adding-columns"><i class="fa fa-check"></i><b>7.3.4</b> Adding columns</a></li>
<li class="chapter" data-level="7.3.5" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#transforming-values"><i class="fa fa-check"></i><b>7.3.5</b> Transforming values</a></li>
<li class="chapter" data-level="7.3.6" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#summarizing"><i class="fa fa-check"></i><b>7.3.6</b> Summarizing</a></li>
<li class="chapter" data-level="7.3.7" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#merging-datasets"><i class="fa fa-check"></i><b>7.3.7</b> Merging datasets</a></li>
<li class="chapter" data-level="7.3.8" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#splitting-datasets"><i class="fa fa-check"></i><b>7.3.8</b> Splitting datasets</a></li>
<li class="chapter" data-level="7.3.9" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#dates"><i class="fa fa-check"></i><b>7.3.9</b> Dates</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#data-management-practical"><i class="fa fa-check"></i><b>7.4</b> Data Management Practical</a></li>
<li class="chapter" data-level="7.5" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#data-management-cross-sectional-feedback"><i class="fa fa-check"></i><b>7.5</b> Data Management (Cross-Sectional) Feedback</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html"><i class="fa fa-check"></i><b>8</b> Data Management - Time Series and Panel Data</a>
<ul>
<li class="chapter" data-level="8.1" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#topic-guide"><i class="fa fa-check"></i><b>8.1</b> Topic Guide:</a></li>
<li class="chapter" data-level="8.2" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#time-series-data"><i class="fa fa-check"></i><b>8.2</b> Time Series Data</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#preliminaries-2"><i class="fa fa-check"></i><b>8.2.1</b> Preliminaries</a></li>
<li class="chapter" data-level="8.2.2" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#convert-to-date-format"><i class="fa fa-check"></i><b>8.2.2</b> Convert to Date Format</a></li>
<li class="chapter" data-level="8.2.3" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#aggregate-data"><i class="fa fa-check"></i><b>8.2.3</b> Aggregate Data</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#modifying-long-and-wide-datasets"><i class="fa fa-check"></i><b>8.3</b> Modifying Long and Wide Datasets</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#how-to-determine"><i class="fa fa-check"></i><b>8.3.1</b> How to Determine</a></li>
<li class="chapter" data-level="8.3.2" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#setting-up-the-dataset"><i class="fa fa-check"></i><b>8.3.2</b> Setting up the Dataset</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#missing-values"><i class="fa fa-check"></i><b>8.4</b> Missing Values</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#setting-up-a-sample-dataset"><i class="fa fa-check"></i><b>8.4.1</b> Setting up a Sample Dataset</a></li>
<li class="chapter" data-level="8.4.2" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#replace-with-0"><i class="fa fa-check"></i><b>8.4.2</b> Replace with <code>0</code></a></li>
<li class="chapter" data-level="8.4.3" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#remove-rows-or-columns-with-missing-values"><i class="fa fa-check"></i><b>8.4.3</b> Remove Rows or Columns with Missing Values</a></li>
<li class="chapter" data-level="8.4.4" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#imputing-missing-values-with-the-mean"><i class="fa fa-check"></i><b>8.4.4</b> Imputing Missing Values with the Mean</a></li>
<li class="chapter" data-level="8.4.5" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#note-1"><i class="fa fa-check"></i><b>8.4.5</b> Note:</a></li>
<li class="chapter" data-level="8.4.6" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#best-practice"><i class="fa fa-check"></i><b>8.4.6</b> Best Practice:</a></li>
<li class="chapter" data-level="8.4.7" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#next-meeting"><i class="fa fa-check"></i><b>8.4.7</b> Next Meeting:</a></li>
<li class="chapter" data-level="8.4.8" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#final-note"><i class="fa fa-check"></i><b>8.4.8</b> Final Note:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html"><i class="fa fa-check"></i><b>9</b> Visualizations using ggplot2</a>
<ul>
<li class="chapter" data-level="9.1" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#preliminaries-3"><i class="fa fa-check"></i><b>9.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#load-the-dataset"><i class="fa fa-check"></i><b>9.1.1</b> Load the dataset</a></li>
<li class="chapter" data-level="9.1.2" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#template"><i class="fa fa-check"></i><b>9.1.2</b> Template</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#visualizing-data-using-geom"><i class="fa fa-check"></i><b>9.2</b> Visualizing Data using <code>geom</code></a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#scatterplots"><i class="fa fa-check"></i><b>9.2.1</b> Scatterplots</a></li>
<li class="chapter" data-level="9.2.2" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#boxplots"><i class="fa fa-check"></i><b>9.2.2</b> Boxplots</a></li>
<li class="chapter" data-level="9.2.3" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#bar-plots"><i class="fa fa-check"></i><b>9.2.3</b> Bar plots</a></li>
<li class="chapter" data-level="9.2.4" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#faceting"><i class="fa fa-check"></i><b>9.2.4</b> Faceting</a></li>
<li class="chapter" data-level="9.2.5" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#pie-chart"><i class="fa fa-check"></i><b>9.2.5</b> Pie Chart</a></li>
<li class="chapter" data-level="9.2.6" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#histogram"><i class="fa fa-check"></i><b>9.2.6</b> Histogram</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#visualizing-time-series-data"><i class="fa fa-check"></i><b>9.3</b> Visualizing Time Series Data</a></li>
<li class="chapter" data-level="9.4" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#practical-visualizations"><i class="fa fa-check"></i><b>9.4</b> Practical: Visualizations</a></li>
<li class="chapter" data-level="9.5" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#feedback-practical-visualizations"><i class="fa fa-check"></i><b>9.5</b> Feedback: Practical Visualizations</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html"><i class="fa fa-check"></i><b>10</b> Advanced Visualizations</a>
<ul>
<li class="chapter" data-level="10.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#preliminaries-4"><i class="fa fa-check"></i><b>10.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#install-packages"><i class="fa fa-check"></i><b>10.1.1</b> Install Packages</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-visualizations"><i class="fa fa-check"></i><b>10.2</b> Animated Visualizations</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-bar-chart"><i class="fa fa-check"></i><b>10.2.1</b> Animated Bar Chart</a></li>
<li class="chapter" data-level="10.2.2" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-scatter-plot"><i class="fa fa-check"></i><b>10.2.2</b> Animated Scatter Plot</a></li>
<li class="chapter" data-level="10.2.3" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-faceted-scatter-plot"><i class="fa fa-check"></i><b>10.2.3</b> Animated Faceted Scatter Plot</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-time-series"><i class="fa fa-check"></i><b>10.3</b> Animated Time Series</a></li>
<li class="chapter" data-level="10.4" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-faceted-time-series"><i class="fa fa-check"></i><b>10.4</b> Animated Faceted Time Series</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#saving-in-quarto"><i class="fa fa-check"></i><b>10.4.1</b> Saving in Quarto</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#maps"><i class="fa fa-check"></i><b>10.5</b> Maps</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#where-to-get-shapefiles"><i class="fa fa-check"></i><b>10.5.1</b> Where to get shapefiles?</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#static-maps"><i class="fa fa-check"></i><b>10.6</b> Static Maps</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#fetching-gdp-data-from-wdi"><i class="fa fa-check"></i><b>10.6.1</b> Fetching GDP Data from WDI</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#philippine-regional-map"><i class="fa fa-check"></i><b>10.7</b> Philippine Regional Map</a></li>
<li class="chapter" data-level="10.8" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-map"><i class="fa fa-check"></i><b>10.8</b> Animated Map</a></li>
<li class="chapter" data-level="10.9" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#practical-advanced-visualizations"><i class="fa fa-check"></i><b>10.9</b> Practical: Advanced Visualizations</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>11</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="11.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#preliminaries-5"><i class="fa fa-check"></i><b>11.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#install-packages-1"><i class="fa fa-check"></i><b>11.1.1</b> Install Packages</a></li>
<li class="chapter" data-level="11.1.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#load-the-dataset-1"><i class="fa fa-check"></i><b>11.1.2</b> Load the dataset</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#frequency-table"><i class="fa fa-check"></i><b>11.2</b> Frequency Table</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#male"><i class="fa fa-check"></i><b>11.2.1</b> Male</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#histogram-1"><i class="fa fa-check"></i><b>11.3</b> Histogram</a></li>
<li class="chapter" data-level="11.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summary-table"><i class="fa fa-check"></i><b>11.4</b> Summary Table</a></li>
<li class="chapter" data-level="11.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#interpretation-of-descriptive-statistics"><i class="fa fa-check"></i><b>11.5</b> Interpretation of Descriptive Statistics:</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#key-components-of-descriptive-statistics"><i class="fa fa-check"></i><b>11.5.1</b> <strong>Key Components of Descriptive Statistics</strong></a></li>
<li class="chapter" data-level="11.5.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#when-to-use-mean-or-median"><i class="fa fa-check"></i><b>11.5.2</b> <strong>When to Use Mean or Median</strong></a></li>
<li class="chapter" data-level="11.5.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#purpose-of-descriptive-statistics"><i class="fa fa-check"></i><b>11.5.3</b> <strong>Purpose of Descriptive Statistics</strong></a></li>
<li class="chapter" data-level="11.5.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#limitations"><i class="fa fa-check"></i><b>11.5.4</b> <strong>Limitations</strong></a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#practical-descriptive-statistics"><i class="fa fa-check"></i><b>11.6</b> Practical: Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#descriptive-statistics-questions"><i class="fa fa-check"></i><b>11.6.1</b> <strong>Descriptive Statistics Questions</strong></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>12</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="12.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#steps-1"><i class="fa fa-check"></i><b>12.1</b> Steps:</a></li>
<li class="chapter" data-level="12.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#difference-between-one-tailed-test-and-two-tailed-test"><i class="fa fa-check"></i><b>12.2</b> Difference between one-tailed test and two-tailed test</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#deciding-between-one-tailed-versus-two-tailed"><i class="fa fa-check"></i><b>12.2.1</b> Deciding between One-Tailed versus Two-Tailed</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#test-of-proportions"><i class="fa fa-check"></i><b>12.3</b> Test of Proportions</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sample-test-of-proportion"><i class="fa fa-check"></i><b>12.3.1</b> <strong>One-Sample Test of Proportion</strong></a></li>
<li class="chapter" data-level="12.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#two-sample-test-of-proportion"><i class="fa fa-check"></i><b>12.3.2</b> <strong>Two-Sample Test of Proportion</strong></a></li>
<li class="chapter" data-level="12.3.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#real-world-example"><i class="fa fa-check"></i><b>12.3.3</b> Real-World Example:</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#t-tests"><i class="fa fa-check"></i><b>12.4</b> T-Tests</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sample-t-test"><i class="fa fa-check"></i><b>12.4.1</b> One-Sample T-Test</a></li>
<li class="chapter" data-level="12.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#real-world-example-1"><i class="fa fa-check"></i><b>12.4.2</b> Real-World Example</a></li>
<li class="chapter" data-level="12.4.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#independent-samples-t-test"><i class="fa fa-check"></i><b>12.4.3</b> Independent-Samples T-Test</a></li>
<li class="chapter" data-level="12.4.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#real-world-example-2"><i class="fa fa-check"></i><b>12.4.4</b> Real-World Example</a></li>
<li class="chapter" data-level="12.4.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#paired-samples-t-test"><i class="fa fa-check"></i><b>12.4.5</b> Paired-Samples T-Test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html"><i class="fa fa-check"></i><b>13</b> Ordinary Least Squares</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#general-description-and-notation-of-a-linear-regression"><i class="fa fa-check"></i><b>13.1</b> <strong>General Description and notation of a Linear Regression</strong></a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#the-notation"><i class="fa fa-check"></i><b>13.1.1</b> The notation</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#running-and-reporting-ols-regression"><i class="fa fa-check"></i><b>13.2</b> <strong>Running and reporting OLS Regression</strong></a></li>
<li class="chapter" data-level="13.3" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#interpretation-of-coefficients"><i class="fa fa-check"></i><b>13.3</b> <strong>Interpretation of Coefficients</strong></a></li>
<li class="chapter" data-level="13.4" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#goodness-of-fit-f-statistics-and-adjusted-r-squared"><i class="fa fa-check"></i><b>13.4</b> <strong>Goodness of Fit (F-Statistics and Adjusted R-squared)</strong></a></li>
<li class="chapter" data-level="13.5" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#assumption-diagnostics"><i class="fa fa-check"></i><b>13.5</b> <strong>Assumption Diagnostics</strong></a></li>
<li class="chapter" data-level="13.6" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#real-world-example-3"><i class="fa fa-check"></i><b>13.6</b> Real-World Example</a></li>
<li class="chapter" data-level="13.7" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#practical-hypothesis-testing-and-ols"><i class="fa fa-check"></i><b>13.7</b> Practical: Hypothesis Testing and OLS</a></li>
<li class="chapter" data-level="13.8" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#hypothesis-testing-1"><i class="fa fa-check"></i><b>13.8</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="13.9" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html#ols"><i class="fa fa-check"></i><b>13.9</b> OLS</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="multivariate-regression-with-dummy-variables.html"><a href="multivariate-regression-with-dummy-variables.html"><i class="fa fa-check"></i><b>14</b> Multivariate Regression with Dummy Variables</a>
<ul>
<li class="chapter" data-level="14.1" data-path="multivariate-regression-with-dummy-variables.html"><a href="multivariate-regression-with-dummy-variables.html#dummy-variables"><i class="fa fa-check"></i><b>14.1</b> Dummy Variables</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="multivariate-regression-with-dummy-variables.html"><a href="multivariate-regression-with-dummy-variables.html#several-related-dummy-variables"><i class="fa fa-check"></i><b>14.1.1</b> Several related dummy variables</a></li>
<li class="chapter" data-level="14.1.2" data-path="multivariate-regression-with-dummy-variables.html"><a href="multivariate-regression-with-dummy-variables.html#dummy-variable-and-continuous-variable-in-regression"><i class="fa fa-check"></i><b>14.1.2</b> Dummy Variable and Continuous Variable in Regression</a></li>
<li class="chapter" data-level="14.1.3" data-path="multivariate-regression-with-dummy-variables.html"><a href="multivariate-regression-with-dummy-variables.html#interaction-terms-with-non-dummy-variables"><i class="fa fa-check"></i><b>14.1.3</b> Interaction terms with non-dummy variables</a></li>
<li class="chapter" data-level="14.1.4" data-path="multivariate-regression-with-dummy-variables.html"><a href="multivariate-regression-with-dummy-variables.html#f-test-for-differences-across-groups"><i class="fa fa-check"></i><b>14.1.4</b> F-test for differences across groups</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html"><i class="fa fa-check"></i><b>15</b> Formal Tests on Assumptions</a>
<ul>
<li class="chapter" data-level="15.1" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#multicollinearity"><i class="fa fa-check"></i><b>15.1</b> Multicollinearity</a></li>
<li class="chapter" data-level="15.2" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#heteroscedasticity"><i class="fa fa-check"></i><b>15.2</b> Heteroscedasticity</a></li>
<li class="chapter" data-level="15.3" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#specification-errors"><i class="fa fa-check"></i><b>15.3</b> Specification Errors</a></li>
<li class="chapter" data-level="15.4" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#alternative-functional-forms"><i class="fa fa-check"></i><b>15.4</b> Alternative Functional Forms</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#log-log-model"><i class="fa fa-check"></i><b>15.4.1</b> Log-Log Model</a></li>
<li class="chapter" data-level="15.4.2" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#log-lin-model"><i class="fa fa-check"></i><b>15.4.2</b> Log-Lin Model</a></li>
<li class="chapter" data-level="15.4.3" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#lin-log-model"><i class="fa fa-check"></i><b>15.4.3</b> Lin-Log Model</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="formal-tests-on-assumptions.html"><a href="formal-tests-on-assumptions.html#practical-multivariate-dummy-regression-and-formal-tests-of-assumptions"><i class="fa fa-check"></i><b>15.5</b> Practical: Multivariate (Dummy) Regression and Formal Tests of Assumptions</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">LBOMETR Course Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-management---cross-sectional-data" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">7</span> Data Management - Cross-Sectional Data<a href="data-management---cross-sectional-data.html#data-management---cross-sectional-data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="where-to-get-data" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Where to Get Data?<a href="data-management---cross-sectional-data.html#where-to-get-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before we proceed to Data Management, let us first find where we can get data for the Data Story Archive. Note that the data you collect should still ensure that you are following the Code of Ethics and analyze Ethical Considerations.</p>
<p>Please view the necessary documents from the Office of the Vice Chancellor for Research and Innovation (<a href="https://www.dlsu.edu.ph/research/research-manual/" class="uri">https://www.dlsu.edu.ph/research/research-manual/</a>)</p>
<p>A list of links you can search and get data from:</p>
<p>Note: I will not include the best links as they are pretty straightforward and these are governmental databases like the ones from World Bank, IMF, UN, Philippine Statistics Authority, and Bangko Sentral ng Pilipinas. The list here is a general list but use with proper discretion.</p>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Link</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Kaggle</td>
<td><a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></td>
<td>Kaggle is where users can provide datasets; it is important to cite the sources. Mostly, datasets in Kaggle can be used for your practice.</td>
</tr>
<tr class="even">
<td>Awesome Public Datasets</td>
<td><a href="https://github.com/awesomedata/awesome-public-datasets" class="uri">https://github.com/awesomedata/awesome-public-datasets</a></td>
<td>This repository is filled with public datasets, mostly from International contexts.</td>
</tr>
<tr class="odd">
<td>Google Dataset Search</td>
<td><a href="https://datasetsearch.research.google.com/" class="uri">https://datasetsearch.research.google.com/</a></td>
<td>You can download publicly available datasets from searching through Google. Though, sometimes the datasets come from ‘Statista.com’. You can check the sources from the search.</td>
</tr>
</tbody>
</table>
</div>
<div id="preliminaries-1" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Preliminaries<a href="data-management---cross-sectional-data.html#preliminaries-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="dataset" class="section level3 hasAnchor" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> Dataset<a href="data-management---cross-sectional-data.html#dataset" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The dataset to be used can be downloaded here: <a href="%22C:/Users/jemma/OneDrive/Documents/DLSU/LBOMETR_Book/Ch2Practice.csv%22">Chapter2 Practice</a> and will be included in the Files in Animospace. The dataset was modified from the Wooldridge package in R as practice material. The particular dataset is the ‘htv’ dataset.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="data-management---cross-sectional-data.html#cb10-1" tabindex="-1"></a><span class="co">#install the wooldridge package. Check previous chapter on how to install packages.</span></span>
<span id="cb10-2"><a href="data-management---cross-sectional-data.html#cb10-2" tabindex="-1"></a><span class="fu">load</span>(wooldridge)</span>
<span id="cb10-3"><a href="data-management---cross-sectional-data.html#cb10-3" tabindex="-1"></a>?htv <span class="co">#to find out about the particular dataset.</span></span></code></pre></div>
<p>NOTE: The htv dataset help will tell you what the variables mean, however, for our practice, we will use the modified version of this dataset.</p>
</div>
<div id="packages-1" class="section level3 hasAnchor" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> Packages<a href="data-management---cross-sectional-data.html#packages-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will mostly use the <code>tidyverse</code> package, in particular, the <code>dplyr</code> package and the <code>tidyr</code> package; double-check in your Packages list whether you have these two packages; if not, you can simply install them.</p>
</div>
<div id="setting-up-the-directory" class="section level3 hasAnchor" number="7.2.3">
<h3><span class="header-section-number">7.2.3</span> Setting up the Directory<a href="data-management---cross-sectional-data.html#setting-up-the-directory" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This is the most important step! Make sure to place the downloaded file in this folder: <strong>DLSU_LBOMETR_Section</strong> in your laptops. Remember, this is your local working directory. This is the working directory you choose. You can set up your working directory in the following ways:</p>
<ol style="list-style-type: decimal">
<li><p>Using the R Studio Menu (works for both Mac and Windows)</p>
<p>a. Go to <strong>Session &gt; Set Working Directory &gt; Choose Working Directory</strong></p></li>
<li><p>Windows:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="data-management---cross-sectional-data.html#cb11-1" tabindex="-1"></a><span class="co"># Use double backslashes `\\` or forward slashes `/`</span></span>
<span id="cb11-2"><a href="data-management---cross-sectional-data.html#cb11-2" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:</span><span class="sc">\\</span><span class="st">Users</span><span class="sc">\\</span><span class="st">YourUsername</span><span class="sc">\\</span><span class="st">Documents&quot;</span>)  <span class="co"># Example with backslashes</span></span>
<span id="cb11-3"><a href="data-management---cross-sectional-data.html#cb11-3" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Users/YourUsername/Documents&quot;</span>)     <span class="co"># Example with forward slashes</span></span></code></pre></div></li>
<li><p>Mac</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="data-management---cross-sectional-data.html#cb12-1" tabindex="-1"></a><span class="co"># Use forward slashes `/`</span></span>
<span id="cb12-2"><a href="data-management---cross-sectional-data.html#cb12-2" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;/Users/YourUsername/Documents&quot;</span>)</span></code></pre></div></li>
</ol>
<p>To check:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="data-management---cross-sectional-data.html#cb13-1" tabindex="-1"></a><span class="fu">getwd</span>()</span></code></pre></div>
</div>
<div id="clean-everything" class="section level3 hasAnchor" number="7.2.4">
<h3><span class="header-section-number">7.2.4</span> Clean Everything<a href="data-management---cross-sectional-data.html#clean-everything" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Do this step every time you use other data or when we do the other chapters.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="data-management---cross-sectional-data.html#cb14-1" tabindex="-1"></a><span class="co"># Remove all objects in the global environment</span></span>
<span id="cb14-2"><a href="data-management---cross-sectional-data.html#cb14-2" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb14-3"><a href="data-management---cross-sectional-data.html#cb14-3" tabindex="-1"></a></span>
<span id="cb14-4"><a href="data-management---cross-sectional-data.html#cb14-4" tabindex="-1"></a><span class="co"># Perform garbage collection to free up memory</span></span>
<span id="cb14-5"><a href="data-management---cross-sectional-data.html#cb14-5" tabindex="-1"></a><span class="fu">gc</span>()</span></code></pre></div>
<pre><code>##           used (Mb) gc trigger  (Mb) max used (Mb)
## Ncells  973422 52.0    1952397 104.3  1314658 70.3
## Vcells 2367100 18.1    8388608  64.0  3336677 25.5</code></pre>
</div>
<div id="importing-the-dataset" class="section level3 hasAnchor" number="7.2.5">
<h3><span class="header-section-number">7.2.5</span> Importing the Dataset<a href="data-management---cross-sectional-data.html#importing-the-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can use the <code>read.csv()</code> to load the <code>csv</code> file into R. Always call the file as something short and easily understandable. Ensure the downloaded file is in the working directory before you load the file. If the downloaded file is not located in the working directory, you will encounter issues.</p>
<p>I will name the file as <code>ch2_p1</code></p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="data-management---cross-sectional-data.html#cb16-1" tabindex="-1"></a>ch2_p1<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">&quot;Ch2Practice.csv&quot;</span>)</span></code></pre></div>
<p>We can use the <code>head()</code> function to inspect the first six rows of the dataset:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="data-management---cross-sectional-data.html#cb17-1" tabindex="-1"></a><span class="fu">head</span>(ch2_p1)</span></code></pre></div>
<pre><code>##        WAGE  ABILITY EDUCATION NORTHEAST NORTHCENTRAL WEST SOUTH EXPERIENCE MOTHEREDUC
## 1 12.019231 5.027738        15        no           no  yes    no          9         12
## 2  8.912656 2.037170        13       yes           no   no    no          8         12
## 3 15.514334 2.475895        15       yes           no   no    no         11         12
## 4 13.333333 3.609240        15       yes           no   no    no          6         12
## 5 11.070110 2.636546        13       yes           no   no    no         15         12
## 6 17.482517 3.474334        18       yes           no   no    no          8         12
##   FATHEREDUC BROKENHOME14 SIBLINGS URBAN X18INNORTHEAST X18INNORTHCENTRAL X18INSOUTH X18INWEST
## 1         12            0        1   yes              1                 0          0         0
## 2         10            1        4   yes              1                 0          0         0
## 3         16            0        2   yes              1                 0          0         0
## 4         12            0        1   yes              1                 0          0         0
## 5         15            1        2   yes              1                 0          0         0
## 6         12            0        2   yes              1                 0          0         0
##   X18INURBAN X17TUITION X18TUITION  LOGWAGE EXPER.2
## 1          1   7.582914   7.260242 2.486508      81
## 2          1   8.595144   9.499537 2.187472      64
## 3          1   7.311346   7.311346 2.741764     121
## 4          1   9.499537  10.162070 2.590267      36
## 5          1   7.311346   7.311346 2.404249     225
## 6          1   7.311346   7.311346 2.861201      64</code></pre>
</div>
</div>
<div id="data-cleaning" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Data Cleaning<a href="data-management---cross-sectional-data.html#data-cleaning" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As you can see, there are 22 columns. Let’s simplify by only choosing the following: WAGE, URBAN, X17TUITION, X18TUITION and EXPER.2. We can do this using the <code>select()</code> function in <code>dplyr</code>. We will save them into a new data frame, <code>ch2_p1.1.</code></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="data-management---cross-sectional-data.html#cb19-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="data-management---cross-sectional-data.html#cb23-1" tabindex="-1"></a>ch2_p1<span class="fl">.1</span><span class="ot">&lt;-</span><span class="fu">select</span>(ch2_p1, <span class="co">#the original dataset </span></span>
<span id="cb23-2"><a href="data-management---cross-sectional-data.html#cb23-2" tabindex="-1"></a>       WAGE, URBAN, X17TUITION, X18TUITION, EXPER<span class="fl">.2</span>)</span></code></pre></div>
<div id="renaming-the-variables" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Renaming the Variables<a href="data-management---cross-sectional-data.html#renaming-the-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will edit the names to much easier conventions. First, let us say that we just want to change them to lowercase names.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="data-management---cross-sectional-data.html#cb24-1" tabindex="-1"></a><span class="fu">names</span>(ch2_p1<span class="fl">.1</span>)<span class="ot">&lt;-</span><span class="fu">tolower</span>(<span class="fu">names</span>(ch2_p1<span class="fl">.1</span>))</span></code></pre></div>
<p>Inspect:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="data-management---cross-sectional-data.html#cb25-1" tabindex="-1"></a><span class="fu">head</span>(ch2_p1<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>##        wage urban x17tuition x18tuition exper.2
## 1 12.019231   yes   7.582914   7.260242      81
## 2  8.912656   yes   8.595144   9.499537      64
## 3 15.514334   yes   7.311346   7.311346     121
## 4 13.333333   yes   9.499537  10.162070      36
## 5 11.070110   yes   7.311346   7.311346     225
## 6 17.482517   yes   7.311346   7.311346      64</code></pre>
<p>Let us change the names of <code>x17tuition, x18tuition,</code>and<code>exper.2</code> to the names similar to what is found in the ‘htv’ dataset: <code>x17tuition</code> to <code>tuit17</code>, <code>x18tuition</code> to <code>tuit18</code> and <code>exper.2</code> to <code>expersq</code> . To do this, we will use the <code>rename()</code> in <code>dplyr</code>. We will also use the (<code>%&gt;%</code>) for this.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="data-management---cross-sectional-data.html#cb27-1" tabindex="-1"></a>ch2_p1<span class="fl">.1</span><span class="ot">&lt;-</span>ch2_p1<span class="fl">.1</span> <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="data-management---cross-sectional-data.html#cb27-2" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb27-3"><a href="data-management---cross-sectional-data.html#cb27-3" tabindex="-1"></a>    <span class="at">tuit17 =</span> x17tuition,</span>
<span id="cb27-4"><a href="data-management---cross-sectional-data.html#cb27-4" tabindex="-1"></a>    <span class="at">tuit18 =</span> x18tuition, </span>
<span id="cb27-5"><a href="data-management---cross-sectional-data.html#cb27-5" tabindex="-1"></a>    <span class="at">expersq =</span> exper<span class="fl">.2</span></span>
<span id="cb27-6"><a href="data-management---cross-sectional-data.html#cb27-6" tabindex="-1"></a>  )</span></code></pre></div>
<p>Inspect again:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="data-management---cross-sectional-data.html#cb28-1" tabindex="-1"></a><span class="fu">head</span>(ch2_p1<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>##        wage urban   tuit17    tuit18 expersq
## 1 12.019231   yes 7.582914  7.260242      81
## 2  8.912656   yes 8.595144  9.499537      64
## 3 15.514334   yes 7.311346  7.311346     121
## 4 13.333333   yes 9.499537 10.162070      36
## 5 11.070110   yes 7.311346  7.311346     225
## 6 17.482517   yes 7.311346  7.311346      64</code></pre>
</div>
<div id="sorting-certain-values" class="section level3 hasAnchor" number="7.3.2">
<h3><span class="header-section-number">7.3.2</span> Sorting certain values<a href="data-management---cross-sectional-data.html#sorting-certain-values" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s say, we want to arrange <code>wage</code>. We will create a different data for this. We use <code>arrange</code> in <code>dplyr</code> package.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="data-management---cross-sectional-data.html#cb30-1" tabindex="-1"></a>ch2_p1sort<span class="ot">&lt;-</span><span class="fu">arrange</span>(ch2_p1<span class="fl">.1</span>,</span>
<span id="cb30-2"><a href="data-management---cross-sectional-data.html#cb30-2" tabindex="-1"></a>                    wage)</span></code></pre></div>
<p>Inspect:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="data-management---cross-sectional-data.html#cb31-1" tabindex="-1"></a><span class="fu">head</span>(ch2_p1sort)</span></code></pre></div>
<pre><code>##       wage urban    tuit17    tuit18 expersq
## 1 1.023529   yes  2.088957  2.251239     169
## 2 1.073345    no  7.520245  7.520245     196
## 3 1.102362   yes  7.355460  6.922371     196
## 4 1.250000   yes  9.417682  8.826549     100
## 5 1.373626   yes  9.692757  9.692757     225
## 6 1.442308    no 11.280367 11.280367      NA</code></pre>
<p>What if you have this kind of data?</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="data-management---cross-sectional-data.html#cb33-1" tabindex="-1"></a><span class="fu">head</span>(ch2_p2)</span></code></pre></div>
<pre><code>##    ch2_p2
## 1 $10,000
## 2 $20,500
## 3 $15,250
## 4 $30,000
## 5 $50,750</code></pre>
<p>Let’s sort this:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="data-management---cross-sectional-data.html#cb35-1" tabindex="-1"></a>ch2_p2sort<span class="ot">&lt;-</span><span class="fu">arrange</span>(ch2_p2)</span>
<span id="cb35-2"><a href="data-management---cross-sectional-data.html#cb35-2" tabindex="-1"></a><span class="fu">head</span>(ch2_p2)</span></code></pre></div>
<pre><code>##    ch2_p2
## 1 $10,000
## 2 $20,500
## 3 $15,250
## 4 $30,000
## 5 $50,750</code></pre>
<p>It did not work. The problem is, <code>ch2_p2</code> is not numeric. We can check:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="data-management---cross-sectional-data.html#cb37-1" tabindex="-1"></a><span class="fu">class</span>(ch2_p2<span class="sc">$</span>ch2_p2)</span></code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<p>We need to make it into a numeric value but we have a <code>,</code> and $. We need to remove them. We use the <code>str_replace</code> function in the <code>stringr</code> package.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="data-management---cross-sectional-data.html#cb39-1" tabindex="-1"></a><span class="fu">library</span>(stringr)</span></code></pre></div>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="data-management---cross-sectional-data.html#cb40-1" tabindex="-1"></a>ch2_p2<span class="sc">$</span>ch2_p2<span class="ot">&lt;-</span><span class="fu">str_replace</span>(</span>
<span id="cb40-2"><a href="data-management---cross-sectional-data.html#cb40-2" tabindex="-1"></a>  ch2_p2<span class="sc">$</span>ch2_p2, <span class="co">#column we want to edit</span></span>
<span id="cb40-3"><a href="data-management---cross-sectional-data.html#cb40-3" tabindex="-1"></a>  <span class="at">pattern =</span> <span class="st">&#39;,&#39;</span>, <span class="co">#what to find</span></span>
<span id="cb40-4"><a href="data-management---cross-sectional-data.html#cb40-4" tabindex="-1"></a>  <span class="at">replacement =</span> <span class="st">&#39;&#39;</span> <span class="co">#what to replace it with</span></span>
<span id="cb40-5"><a href="data-management---cross-sectional-data.html#cb40-5" tabindex="-1"></a>)</span></code></pre></div>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="data-management---cross-sectional-data.html#cb41-1" tabindex="-1"></a><span class="fu">head</span>(ch2_p2)</span></code></pre></div>
<pre><code>##   ch2_p2
## 1 $10000
## 2 $20500
## 3 $15250
## 4 $30000
## 5 $50750</code></pre>
<p>Now, let us remove the dollar sign; usually, simply doing the same thing we did with the comma works, but, there are some symbols that are used as “special character”. To “force” R to replace the presence of ‘$’, we add two backslashes before the dollar sign.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="data-management---cross-sectional-data.html#cb43-1" tabindex="-1"></a>ch2_p2<span class="sc">$</span>ch2_p2<span class="ot">&lt;-</span><span class="fu">str_replace</span>(</span>
<span id="cb43-2"><a href="data-management---cross-sectional-data.html#cb43-2" tabindex="-1"></a>  ch2_p2<span class="sc">$</span>ch2_p2, </span>
<span id="cb43-3"><a href="data-management---cross-sectional-data.html#cb43-3" tabindex="-1"></a>  <span class="at">pattern =</span> <span class="st">&#39;</span><span class="sc">\\</span><span class="st">$&#39;</span>,</span>
<span id="cb43-4"><a href="data-management---cross-sectional-data.html#cb43-4" tabindex="-1"></a>  <span class="at">replacement =</span> <span class="st">&#39;&#39;</span></span>
<span id="cb43-5"><a href="data-management---cross-sectional-data.html#cb43-5" tabindex="-1"></a>)</span></code></pre></div>
<p>Can you inspect it on your own?</p>
<p>Simply type the code in the empty code chunk then run it by pressing <strong>Ctrl+Enter</strong> or <strong>Cmd+Enter</strong></p>
<p>Now, sort <code>ch2_p2</code></p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="data-management---cross-sectional-data.html#cb44-1" tabindex="-1"></a>ch2_p2sort<span class="ot">&lt;-</span><span class="fu">arrange</span>(</span>
<span id="cb44-2"><a href="data-management---cross-sectional-data.html#cb44-2" tabindex="-1"></a>  ch2_p2,</span>
<span id="cb44-3"><a href="data-management---cross-sectional-data.html#cb44-3" tabindex="-1"></a>  ch2_p2</span>
<span id="cb44-4"><a href="data-management---cross-sectional-data.html#cb44-4" tabindex="-1"></a>)</span></code></pre></div>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="data-management---cross-sectional-data.html#cb45-1" tabindex="-1"></a><span class="fu">head</span>(ch2_p2sort)</span></code></pre></div>
<pre><code>##   ch2_p2
## 1  10000
## 2  15250
## 3  20500
## 4  30000
## 5  50750</code></pre>
<p>We can see that it was arranged, however, take a look at the way ch2_p2 was encoded; it is not numeric. So, we need to change this.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="data-management---cross-sectional-data.html#cb47-1" tabindex="-1"></a><span class="fu">class</span>(ch2_p2<span class="sc">$</span>ch2_p2)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>Change to numeric through <code>as.numeric()</code></p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="data-management---cross-sectional-data.html#cb49-1" tabindex="-1"></a>ch2_p2<span class="sc">$</span>ch2_p2<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(ch2_p2<span class="sc">$</span>ch2_p2)</span></code></pre></div>
<p>Inspect on your own:</p>
</div>
<div id="pipe-operator" class="section level3 hasAnchor" number="7.3.3">
<h3><span class="header-section-number">7.3.3</span> Pipe Operator<a href="data-management---cross-sectional-data.html#pipe-operator" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>%&gt;%</code> allows functions to be chained; it can be read as “then” - it tells R to do whatever comes after it to the stuff that comes before it.</p>
</div>
<div id="adding-columns" class="section level3 hasAnchor" number="7.3.4">
<h3><span class="header-section-number">7.3.4</span> Adding columns<a href="data-management---cross-sectional-data.html#adding-columns" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will be using the pipe operator and the <code>mutate</code> to add a new column to <code>ch2_p1.1</code> based from details found in <code>ch2_p1</code>, particularly, NORTHEAST, NORTHCENTRAL, WEST, and SOUTH. We will call this new column as <code>location</code></p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="data-management---cross-sectional-data.html#cb50-1" tabindex="-1"></a>ch2_p1<span class="fl">.1</span><span class="ot">&lt;-</span>ch2_p1<span class="fl">.1</span> <span class="sc">%&gt;%</span> </span>
<span id="cb50-2"><a href="data-management---cross-sectional-data.html#cb50-2" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb50-3"><a href="data-management---cross-sectional-data.html#cb50-3" tabindex="-1"></a>    <span class="at">location =</span> <span class="fu">case_when</span>( <span class="co">#creates conditional statements</span></span>
<span id="cb50-4"><a href="data-management---cross-sectional-data.html#cb50-4" tabindex="-1"></a>      ch2_p1<span class="sc">$</span>NORTHEAST <span class="sc">==</span> <span class="st">&quot;yes&quot;</span> <span class="sc">~</span> <span class="st">&quot;northeast&quot;</span>, <span class="co">#If NE is &quot;yes&quot;, location is &quot;northeast&quot;</span></span>
<span id="cb50-5"><a href="data-management---cross-sectional-data.html#cb50-5" tabindex="-1"></a>    ch2_p1<span class="sc">$</span>WEST <span class="sc">==</span> <span class="st">&quot;yes&quot;</span><span class="sc">~</span><span class="st">&quot;west&quot;</span>, <span class="co">#If WEST is &quot;yes&quot;, location is &quot;west&quot;</span></span>
<span id="cb50-6"><a href="data-management---cross-sectional-data.html#cb50-6" tabindex="-1"></a>    ch2_p1<span class="sc">$</span>NORTHCENTRAL <span class="sc">==</span> <span class="st">&quot;yes&quot;</span><span class="sc">~</span> <span class="st">&quot;northcen&quot;</span>,</span>
<span id="cb50-7"><a href="data-management---cross-sectional-data.html#cb50-7" tabindex="-1"></a>      ch2_p1<span class="sc">$</span>SOUTH <span class="sc">==</span> <span class="st">&quot;yes&quot;</span><span class="sc">~</span> <span class="st">&quot;south&quot;</span>,</span>
<span id="cb50-8"><a href="data-management---cross-sectional-data.html#cb50-8" tabindex="-1"></a>    <span class="cn">TRUE</span><span class="sc">~</span><span class="st">&quot;other&quot;</span>)</span>
<span id="cb50-9"><a href="data-management---cross-sectional-data.html#cb50-9" tabindex="-1"></a>  )</span></code></pre></div>
<p>Inspect the data:</p>
<p>Now I want you to create a new column called, <code>tuit_diff</code> wherein it is the difference between <code>tuit18</code> and <code>tuit17</code>. In this case, there is no need to use <code>case_when</code> since there is no conditional statements to be used. It is straightforward that you simply need to subtract <code>tuit17</code> from <code>tuit18</code>. You will need to use <code>mutate</code> still. How will you create that?</p>
</div>
<div id="transforming-values" class="section level3 hasAnchor" number="7.3.5">
<h3><span class="header-section-number">7.3.5</span> Transforming values<a href="data-management---cross-sectional-data.html#transforming-values" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now, you can see that urban is a <code>character</code> that is “yes/no”. We need to change that to numeric value. This is particularly useful when we use dummy variables later on. We will not use <code>case_when</code> as it is not necessary; rather, we will use <code>ifelse</code>:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="data-management---cross-sectional-data.html#cb51-1" tabindex="-1"></a>ch2_p1<span class="fl">.1</span><span class="ot">&lt;-</span>ch2_p1<span class="fl">.1</span> <span class="sc">%&gt;%</span> </span>
<span id="cb51-2"><a href="data-management---cross-sectional-data.html#cb51-2" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb51-3"><a href="data-management---cross-sectional-data.html#cb51-3" tabindex="-1"></a>    <span class="at">urban =</span> <span class="fu">ifelse</span>(urban<span class="sc">==</span><span class="st">&quot;yes&quot;</span>, <span class="dv">1</span>,<span class="dv">0</span>) <span class="co">#replace &quot;yes&quot; with 1 and &quot;no&quot; with 0</span></span>
<span id="cb51-4"><a href="data-management---cross-sectional-data.html#cb51-4" tabindex="-1"></a>  )</span>
<span id="cb51-5"><a href="data-management---cross-sectional-data.html#cb51-5" tabindex="-1"></a><span class="fu">head</span>(ch2_p1<span class="fl">.1</span>) <span class="co">#default is first 6 rows</span></span></code></pre></div>
<pre><code>##        wage urban   tuit17    tuit18 expersq  location
## 1 12.019231     1 7.582914  7.260242      81      west
## 2  8.912656     1 8.595144  9.499537      64 northeast
## 3 15.514334     1 7.311346  7.311346     121 northeast
## 4 13.333333     1 9.499537 10.162070      36 northeast
## 5 11.070110     1 7.311346  7.311346     225 northeast
## 6 17.482517     1 7.311346  7.311346      64 northeast</code></pre>
<p>Now, I want you to create groups for <code>expersq</code>. <code>NA</code> should now be 0, assign 1 if less than 50, assign 2 if between 50 and 100, assign 3 if between 100 and 200, and for the rest, assign 4.</p>
<p>Clue: conditional statements like between 50 and 100 should be like this:</p>
<p><code>values&gt;=50 &amp; values &lt; 100</code></p>
<p>Your answer should look like this:</p>
<pre><code>##        wage urban   tuit17    tuit18 expersq  location
## 1 12.019231     1 7.582914  7.260242       2      west
## 2  8.912656     1 8.595144  9.499537       2 northeast
## 3 15.514334     1 7.311346  7.311346       3 northeast
## 4 13.333333     1 9.499537 10.162070       1 northeast
## 5 11.070110     1 7.311346  7.311346       4 northeast
## 6 17.482517     1 7.311346  7.311346       2 northeast</code></pre>
</div>
<div id="summarizing" class="section level3 hasAnchor" number="7.3.6">
<h3><span class="header-section-number">7.3.6</span> Summarizing<a href="data-management---cross-sectional-data.html#summarizing" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let us get the average of wages by location, which we’ll call <code>ave.wage</code>, by using the <code>group_by()</code> and <code>summarise()</code> functions in dplyr</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="data-management---cross-sectional-data.html#cb54-1" tabindex="-1"></a>ch2_p1<span class="fl">.1</span>ave<span class="ot">&lt;-</span>ch2_p1<span class="fl">.1</span> <span class="sc">%&gt;%</span> </span>
<span id="cb54-2"><a href="data-management---cross-sectional-data.html#cb54-2" tabindex="-1"></a>  <span class="fu">group_by</span>(location) <span class="sc">%&gt;%</span> <span class="co">#group by location, THEN</span></span>
<span id="cb54-3"><a href="data-management---cross-sectional-data.html#cb54-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">ave.wage=</span><span class="fu">mean</span>(wage)) <span class="co">#calculate the mean of wages for each location</span></span>
<span id="cb54-4"><a href="data-management---cross-sectional-data.html#cb54-4" tabindex="-1"></a><span class="fu">head</span>(ch2_p1<span class="fl">.1</span>ave)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 2
##   location  ave.wage
##   &lt;chr&gt;        &lt;dbl&gt;
## 1 northcen      12.5
## 2 northeast     15.0
## 3 south         12.4
## 4 west          14.1</code></pre>
<p>Say that you want to see the average wage in the south area. We can do this by using <code>filter()</code></p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="data-management---cross-sectional-data.html#cb56-1" tabindex="-1"></a>ch2_p1<span class="fl">.1</span>ave <span class="sc">%&gt;%</span> <span class="fu">filter</span>(location<span class="sc">==</span><span class="st">&quot;south&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   location ave.wage
##   &lt;chr&gt;       &lt;dbl&gt;
## 1 south        12.4</code></pre>
<p>How would you sort the dataset by average wage, from highest to lowest? Now you see that it is arranged alphabetically, so how will you arrange it?</p>
</div>
<div id="merging-datasets" class="section level3 hasAnchor" number="7.3.7">
<h3><span class="header-section-number">7.3.7</span> Merging datasets<a href="data-management---cross-sectional-data.html#merging-datasets" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We have two main datasets, <code>ch2_p1.1</code> and <code>ch2_p1.1ave</code>. By doing this, we could compare side-by-side each observation compared to the average per location.</p>
<p>We will join the datasets by <code>location</code> variable, since that is consistent across both datasets. We name the new file as <code>ch2_p1merged</code>:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="data-management---cross-sectional-data.html#cb58-1" tabindex="-1"></a>ch2_p1merged<span class="ot">&lt;-</span><span class="fu">merge</span>(<span class="at">x=</span>ch2_p1<span class="fl">.1</span>, <span class="at">y=</span>ch2_p1<span class="fl">.1</span>ave, <span class="at">by=</span><span class="st">&quot;location&quot;</span>)</span>
<span id="cb58-2"><a href="data-management---cross-sectional-data.html#cb58-2" tabindex="-1"></a><span class="fu">head</span>(ch2_p1merged)</span></code></pre></div>
<pre><code>##   location      wage urban   tuit17   tuit18 expersq ave.wage
## 1 northcen 15.294118     1 8.334936 8.334936       3 12.54078
## 2 northcen 17.006804     1 8.334936 8.334936       0 12.54078
## 3 northcen  3.755868     1 8.334936 8.334936       3 12.54078
## 4 northcen  5.288462     1 6.742574 7.198132       2 12.54078
## 5 northcen  9.072165     1 7.305873 7.356897       0 12.54078
## 6 northcen  9.384164     1 8.334936 8.334936       3 12.54078</code></pre>
</div>
<div id="splitting-datasets" class="section level3 hasAnchor" number="7.3.8">
<h3><span class="header-section-number">7.3.8</span> Splitting datasets<a href="data-management---cross-sectional-data.html#splitting-datasets" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Say I want to save different datasets based on the <code>location</code> column.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="data-management---cross-sectional-data.html#cb60-1" tabindex="-1"></a>northcen_data<span class="ot">&lt;-</span>ch2_p1<span class="fl">.1</span> <span class="sc">%&gt;%</span> <span class="fu">filter</span>(location<span class="sc">==</span><span class="st">&quot;northcen&quot;</span>)</span></code></pre></div>
<p>You can save it as a <code>.csv</code> file:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="data-management---cross-sectional-data.html#cb61-1" tabindex="-1"></a><span class="fu">write.csv</span>(northcen_data, <span class="st">&quot;northcentral.csv&quot;</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>Can you do the others?</p>
</div>
<div id="dates" class="section level3 hasAnchor" number="7.3.9">
<h3><span class="header-section-number">7.3.9</span> Dates<a href="data-management---cross-sectional-data.html#dates" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We are going to work on dates when we move to the next chapter but, here is something initial and necessary.</p>
<pre><code>##   ID date_of_birth
## 1  1    15-05-1990
## 2  2    20-08-1985
## 3  3    01-12-2000
## 4  4    10-03-1995
## 5  5    25-07-2010</code></pre>
<pre><code>## &#39;data.frame&#39;:    5 obs. of  2 variables:
##  $ ID           : int  1 2 3 4 5
##  $ date_of_birth: chr  &quot;15-05-1990&quot; &quot;20-08-1985&quot; &quot;01-12-2000&quot; &quot;10-03-1995&quot; ...</code></pre>
<p>To convert the <code>character</code> format to date format, we do this:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="data-management---cross-sectional-data.html#cb64-1" tabindex="-1"></a>date_data<span class="sc">$</span>date_of_birth <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(date_data<span class="sc">$</span>date_of_birth, <span class="at">format =</span> <span class="st">&quot;%d-%m-%Y&quot;</span>)</span>
<span id="cb64-2"><a href="data-management---cross-sectional-data.html#cb64-2" tabindex="-1"></a></span>
<span id="cb64-3"><a href="data-management---cross-sectional-data.html#cb64-3" tabindex="-1"></a><span class="fu">head</span>(date_data)</span></code></pre></div>
<pre><code>##   ID date_of_birth
## 1  1    1990-05-15
## 2  2    1985-08-20
## 3  3    2000-12-01
## 4  4    1995-03-10
## 5  5    2010-07-25</code></pre>
<p>Say you want to calculate the age:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="data-management---cross-sectional-data.html#cb66-1" tabindex="-1"></a>date_data<span class="sc">$</span>age <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">floor</span>((<span class="fu">Sys.Date</span>()<span class="sc">-</span>date_data<span class="sc">$</span>date_of_birth)<span class="sc">/</span><span class="fl">365.25</span>))</span>
<span id="cb66-2"><a href="data-management---cross-sectional-data.html#cb66-2" tabindex="-1"></a><span class="fu">head</span>(date_data)</span></code></pre></div>
<pre><code>##   ID date_of_birth age
## 1  1    1990-05-15  35
## 2  2    1985-08-20  39
## 3  3    2000-12-01  24
## 4  4    1995-03-10  30
## 5  5    2010-07-25  14</code></pre>
<div id="custom-reference-date" class="section level4 hasAnchor" number="7.3.9.1">
<h4><span class="header-section-number">7.3.9.1</span> Custom Reference Date:<a href="data-management---cross-sectional-data.html#custom-reference-date" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="data-management---cross-sectional-data.html#cb68-1" tabindex="-1"></a>ref_date<span class="ot">&lt;-</span><span class="fu">as.Date</span>(<span class="st">&quot;2020-01-01&quot;</span>)</span>
<span id="cb68-2"><a href="data-management---cross-sectional-data.html#cb68-2" tabindex="-1"></a>date_data<span class="sc">$</span>age2<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">floor</span>((ref_date<span class="sc">-</span>date_data<span class="sc">$</span>date_of_birth)<span class="sc">/</span><span class="fl">365.25</span>))</span>
<span id="cb68-3"><a href="data-management---cross-sectional-data.html#cb68-3" tabindex="-1"></a><span class="fu">head</span>(date_data)</span></code></pre></div>
<pre><code>##   ID date_of_birth age age2
## 1  1    1990-05-15  35   29
## 2  2    1985-08-20  39   34
## 3  3    2000-12-01  24   19
## 4  4    1995-03-10  30   24
## 5  5    2010-07-25  14    9</code></pre>
</div>
</div>
</div>
<div id="data-management-practical" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Data Management Practical<a href="data-management---cross-sectional-data.html#data-management-practical" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In your Quarto Markdown files, you need to answer the following questions. Answers will be given the week after the Practical as a form of Feedback. You can answer by group. It would be great to include which group member did what.</p>
<p>In the first part of the practical, answer the following reflection:</p>
<ol style="list-style-type: decimal">
<li>Do you think you were able to input correctly all the codes in the empty code chunks? Why do you think so? What did you find difficult?</li>
</ol>
<p>Now comes the practical proper:</p>
<p>Using the <code>kpop idols</code> dataset which you download: <a href="%22C:/Users/jemma/OneDrive/Documents/DLSU/LBOMETR_Book/kpop%20idols.csv%22">Practical 1</a> - also made available in Animospace, answer the questions.</p>
<p>Ensure that you can render individually before uploading in your shared Google Drive. Failure to render the file means you were unable to do the Practical. The leader must take note of this since accomplishing the practicals are part of your grade in Group Participation and the Data Story Archive.</p>
<ol style="list-style-type: decimal">
<li>Separate the dataset into two datasets: one for <code>males</code> and one for females. Save these datasets as <code>males.csv</code> and <code>females.csv</code></li>
<li>Edit the column names for both <code>males</code> and <code>females</code> datasets to make them shorter, easier to understand, and consistent</li>
<li>Remove the following columns from both datasets: Instagram, Korean Name, K.Stage Name, Stage Name</li>
<li>How many males and females are in the dataset? <em>Hint:</em> <code>nrow()</code></li>
<li>Create a binary variable <code>not_seoul</code> for both datasets.
<ol style="list-style-type: decimal">
<li>Assign <code>1</code> if <code>birthplace</code> is <strong>not Seoul,</strong> and <code>0</code> otherwise</li>
<li>Count how many individuals are from Seoul and how many are not for both datasets.</li>
</ol></li>
<li>How many males are eligible for military service (ages 18-28 as of February 27, 2024)?
<ol style="list-style-type: decimal">
<li>Filter the <code>males</code> dataset for this age range, how many from the Country of South Korea (only filter according to Country for straightforwardness) and count how many qualify.</li>
</ol></li>
<li>Assign generations based on age (as of June 29, 2023 when the Korean Age system was abolished) for both datasets.
<ol style="list-style-type: decimal">
<li><p>Generation criteria:</p>
<ol style="list-style-type: decimal">
<li>1st Gen: Age&gt;=40</li>
<li>2nd Gen: 31&lt;=Age&lt;=39</li>
<li>3rd Gen: 25&lt;=Age&lt;=30</li>
<li>4th Gen: Age&lt;=24</li>
</ol>
<p>Count the number of individuals in each generation for males and females</p></li>
</ol></li>
<li>Create a new column <code>income</code> for both datasets using hypothetical values based from your hypothesis on age influencing income levels of idols. Explain first what your hypothesis is - are idols who are older earning more or less? Why or why not? Also think if you believe females earn more than males or vice versa?
<ol style="list-style-type: decimal">
<li>Use <code>set.seed()</code> for reproducibility and generate random income values.
<ol style="list-style-type: decimal">
<li>Please have different income values depending on their age. You can do similar groupings as Step 7 for this.</li>
</ol></li>
<li>Compare the mean income</li>
</ol></li>
<li>Combine the <code>males</code> and <code>females</code> datasets</li>
<li>Calculate the income difference between males and females
<ol style="list-style-type: decimal">
<li>Create a column <code>income_diff</code> to calculate how much more or less each individual’s income is compared to the average income of the other gender.</li>
</ol></li>
<li>Save the final dataset named <strong>Ch2_Practical_Section_GrpNo.csv</strong></li>
</ol>
</div>
<div id="data-management-cross-sectional-feedback" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> Data Management (Cross-Sectional) Feedback<a href="data-management---cross-sectional-data.html#data-management-cross-sectional-feedback" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This feedback will contain only what the answers should look like and some clues and hints. It does not contain the entire codes.</p>
<ol style="list-style-type: decimal">
<li>Loading the dataset and loading the needed libraries: <code>dplyr</code> and <code>lubridate</code></li>
</ol>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     date, intersect, setdiff, union</code></pre>
<pre><code>##   Stage.Name.Stage.Name Full.Name.Full.Name Korean.Name.Korean.Name
## 1               Taeyeon         Kim Taeyeon                  김태연
## 2                 Sunny          Lee Sunkyu                  이순규
## 3               Tiffany       Hwang Miyoung                  황미영
## 4               Hyoyeon         Kim Hyoyeon                  김효연
## 5                  Yuri           Kwon Yuri                  권유리
## 6              Sooyoung       Choi Sooyoung                  최수영
##   K..Stage.Name.K..Stage.Name Date.of.Birth.Date.of.Birth Group.Group Country.Country
## 1                        태연                    3/9/1989        SNSD     South Korea
## 2                        써니                   5/15/1989        SNSD     South Korea
## 3                      티파니                    8/1/1989        SNSD     South Korea
## 4                        효연                   9/22/1989        SNSD     South Korea
## 5                        유리                   12/5/1989        SNSD     South Korea
## 6                        수영                   2/10/1990        SNSD     South Korea
##   Height.Height Weight.Weight Birthplace.Birthplace Gender.Gender Instagram.Instagram
## 1           160            44                Jeonju             F          taeyeon_ss
## 2           158            43            California             F          svnnynight
## 3           163            50         San Francisco             F        xolovestephi
## 4           158            48               Incheon             F         watasiwahyo
## 5           167            45                Goyang             F             yulyulk
## 6           170            48               Gwangju             F          hotsootuff</code></pre>
<ol start="2" style="list-style-type: decimal">
<li><p>Separate the dataset into Males and Females and save as CSVs. You might notice that the column name is <code>Gender.Gender</code>. You have to type it out. Later, we will change the names.</p>
<pre><code>##   Stage.Name.Stage.Name Full.Name.Full.Name Korean.Name.Korean.Name
## 1                 T.O.P      Choi Seunghyun                  최승현
## 2               Taeyang       Dong Youngbae                  동영배
## 3              G-Dragon         Kwon Jiyong                  권지용
## 4               Daesung             Daesung                  강대성
## 5               Seungri       Lee Seunghyun                  이승현
## 6               Leeteuk        Park Jeongsu                  박정수
##   K..Stage.Name.K..Stage.Name Date.of.Birth.Date.of.Birth  Group.Group Country.Country
## 1                          탑                   11/4/1987      BIGBANG     South Korea
## 2                        태양                   5/18/1988      BIGBANG     South Korea
## 3                    지드래곤                   8/18/1988      BIGBANG     South Korea
## 4                        대성                   4/26/1989      BIGBANG     South Korea
## 5                        승리                  12/12/1990                  South Korea
## 6                        이특                    7/1/1983 Super Junior     South Korea
##   Height.Height Weight.Weight Birthplace.Birthplace Gender.Gender Instagram.Instagram
## 1           180            65                 Seoul             M                    
## 2           174            56             Uljeongbu             M                    
## 3           177            58                 Seoul             M                    
## 4           178            63               Incheon             M                    
## 5           176            60               Gwangju             M                    
## 6           179            59                 Seoul             M</code></pre>
<pre><code>##   Stage.Name.Stage.Name Full.Name.Full.Name Korean.Name.Korean.Name
## 1               Taeyeon         Kim Taeyeon                  김태연
## 2                 Sunny          Lee Sunkyu                  이순규
## 3               Tiffany       Hwang Miyoung                  황미영
## 4               Hyoyeon         Kim Hyoyeon                  김효연
## 5                  Yuri           Kwon Yuri                  권유리
## 6              Sooyoung       Choi Sooyoung                  최수영
##   K..Stage.Name.K..Stage.Name Date.of.Birth.Date.of.Birth Group.Group Country.Country
## 1                        태연                    3/9/1989        SNSD     South Korea
## 2                        써니                   5/15/1989        SNSD     South Korea
## 3                      티파니                    8/1/1989        SNSD     South Korea
## 4                        효연                   9/22/1989        SNSD     South Korea
## 5                        유리                   12/5/1989        SNSD     South Korea
## 6                        수영                   2/10/1990        SNSD     South Korea
##   Height.Height Weight.Weight Birthplace.Birthplace Gender.Gender Instagram.Instagram
## 1           160            44                Jeonju             F          taeyeon_ss
## 2           158            43            California             F          svnnynight
## 3           163            50         San Francisco             F        xolovestephi
## 4           158            48               Incheon             F         watasiwahyo
## 5           167            45                Goyang             F             yulyulk
## 6           170            48               Gwangju             F          hotsootuff</code></pre></li>
<li><p>Edit Column Names and Remove Unnecessary Columns</p></li>
</ol>
<pre><code>We are going to use the pipe operator for this and if you are lazy to type all the column names you need to remove, you can create like a collection of the columns you will keep.


``` r
#only those that remain
#col&lt;-c(&quot;Full.Name.Full.Name&quot;, &quot;Date.of.Birth.Date.of.Birth&quot;...)
```

THEN, after you select the columns to keep, you can rename. Note that you need to follow the old conventions for R to find the column names before renaming them using `rename`. In the `rename`, say


```
##       Full_Name       DOB  Grp     Country  Ht Wt            BP Gender
## 1   Kim Taeyeon  3/9/1989 SNSD South Korea 160 44        Jeonju      F
## 2    Lee Sunkyu 5/15/1989 SNSD South Korea 158 43    California      F
## 3 Hwang Miyoung  8/1/1989 SNSD South Korea 163 50 San Francisco      F
## 4   Kim Hyoyeon 9/22/1989 SNSD South Korea 158 48       Incheon      F
## 5     Kwon Yuri 12/5/1989 SNSD South Korea 167 45        Goyang      F
## 6 Choi Sooyoung 2/10/1990 SNSD South Korea 170 48       Gwangju      F
```

```
##        Full_Name        DOB          Grp     Country  Ht Wt        BP Gender
## 1 Choi Seunghyun  11/4/1987      BIGBANG South Korea 180 65     Seoul      M
## 2  Dong Youngbae  5/18/1988      BIGBANG South Korea 174 56 Uljeongbu      M
## 3    Kwon Jiyong  8/18/1988      BIGBANG South Korea 177 58     Seoul      M
## 4        Daesung  4/26/1989      BIGBANG South Korea 178 63   Incheon      M
## 5  Lee Seunghyun 12/12/1990              South Korea 176 60   Gwangju      M
## 6   Park Jeongsu   7/1/1983 Super Junior South Korea 179 59     Seoul      M
```</code></pre>
<ol start="4" style="list-style-type: decimal">
<li><p>Count the Number of Males and Females</p>
<p>As mentioned, use <code>nrow</code>. Now, I will introduce you to the <code>cat</code> function, The <code>cat</code> function will print in the result some text and what will be seen when you include the object you created that reveals the number of males (or females). We should all have the same number. If not, something is wrong.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="data-management---cross-sectional-data.html#cb76-1" tabindex="-1"></a><span class="co">#cat(&quot;Number of males:&quot;, nummale,&quot;\n&quot;)</span></span></code></pre></div>
<pre><code>## Number of males: 843</code></pre>
<pre><code>## Number of females: 823</code></pre></li>
<li><p>Create a binary variable <code>not_seoul</code></p>
<p>Here, create a new column for not_seoul in both males and females. Use <code>ifelse</code> and the statement should include <code>!=</code></p></li>
<li><p>Count Individuals from and not from Seoul</p>
<p>I introduce the <code>count</code> function. Simply add <code>count</code> after choosing the dataset. So, the code is choose males THEN count those that are not_seoul. We should have the same number.</p>
<pre><code>## Males from Seoul and not Seoul:</code></pre>
<pre><code>## From Seoul: 98</code></pre>
<pre><code>## Not from Seoul: 745</code></pre>
<pre><code>## Females from Seoul and not Seoul:</code></pre>
<pre><code>## From Seoul: 108</code></pre>
<pre><code>## Not from Seoul: 715</code></pre></li>
<li><p>Filter Males Eligible for Military Service</p>
<p>Use reference date and when you filter, you can actually combine filtering the Age to be: Age<code>&gt;= 18, Age&lt;=28, Country == "South Korea"</code>. We should have the same number.</p></li>
</ol>
<pre><code>## Number of males eligible for military service: 496</code></pre>
<ol start="8" style="list-style-type: decimal">
<li><p>Assign Generations Based on Age</p>
<p>We should have the same numbers. If you have created an <code>Age</code> column for males before, you cannot use that for this number since the reference dates are different. You need to create a new column for <code>Age</code> for both males and females.</p>
<pre><code>## Generation distribution for males:</code></pre>
<pre><code>## 1st Gen: 8
## 2nd Gen: 137
## 3rd Gen: 358
## 4th Gen: 340</code></pre>
<pre><code>## Generation distribution for females:</code></pre>
<pre><code>## 1st Gen: 4
## 2nd Gen: 131
## 3rd Gen: 302
## 4th Gen: 386</code></pre></li>
<li><p>Create Income Column Based on Hypothesis</p>
<p>My hypothesis is that older idols earn more since they have been in the industry much longer. I also hypothesize that females earn less than males.</p>
<p>I introduce a new function here, it is the <code>runif(n(), value, value)</code>. This function is to just create income values which will be in-line with the number of rows in the dataset. However, I am amenable in any strategy you employ to generate income here. I just need to know your hypothesis and how you plan to do the income column. In fact, if you want, you can even create the income column in Excel already. Just let me know.</p>
<p>Another strategy is to still do <code>case_when</code> and have smaller increments in <code>Age</code> then have income values. Another, have the same income for each generation, that is also fine. Again, this is for practice purposes.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="data-management---cross-sectional-data.html#cb90-1" tabindex="-1"></a><span class="co"># Generate income values based on age group directly</span></span>
<span id="cb90-2"><a href="data-management---cross-sectional-data.html#cb90-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># For reproducibility</span></span>
<span id="cb90-3"><a href="data-management---cross-sectional-data.html#cb90-3" tabindex="-1"></a></span>
<span id="cb90-4"><a href="data-management---cross-sectional-data.html#cb90-4" tabindex="-1"></a>males <span class="ot">&lt;-</span> males <span class="sc">%&gt;%</span></span>
<span id="cb90-5"><a href="data-management---cross-sectional-data.html#cb90-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Income =</span> <span class="fu">case_when</span>(</span>
<span id="cb90-6"><a href="data-management---cross-sectional-data.html#cb90-6" tabindex="-1"></a>    Age2 <span class="sc">&gt;=</span> <span class="dv">40</span> <span class="sc">~</span> <span class="fu">runif</span>(<span class="fu">n</span>(), <span class="dv">50000</span>, <span class="dv">70000</span>),  <span class="co"># 1st Gen</span></span>
<span id="cb90-7"><a href="data-management---cross-sectional-data.html#cb90-7" tabindex="-1"></a>    Age2 <span class="sc">&gt;=</span> <span class="dv">31</span> <span class="sc">&amp;</span> Age2 <span class="sc">&lt;=</span> <span class="dv">39</span> <span class="sc">~</span> <span class="fu">runif</span>(<span class="fu">n</span>(), <span class="dv">40000</span>, <span class="dv">60000</span>),  <span class="co"># 2nd Gen</span></span>
<span id="cb90-8"><a href="data-management---cross-sectional-data.html#cb90-8" tabindex="-1"></a>    Age2 <span class="sc">&gt;=</span> <span class="dv">25</span> <span class="sc">&amp;</span> Age2 <span class="sc">&lt;=</span> <span class="dv">30</span> <span class="sc">~</span> <span class="fu">runif</span>(<span class="fu">n</span>(), <span class="dv">30000</span>, <span class="dv">50000</span>),  <span class="co"># 3rd Gen</span></span>
<span id="cb90-9"><a href="data-management---cross-sectional-data.html#cb90-9" tabindex="-1"></a>    Age2 <span class="sc">&lt;=</span> <span class="dv">24</span> <span class="sc">~</span> <span class="fu">runif</span>(<span class="fu">n</span>(), <span class="dv">20000</span>, <span class="dv">40000</span>)  <span class="co"># 4th Gen</span></span>
<span id="cb90-10"><a href="data-management---cross-sectional-data.html#cb90-10" tabindex="-1"></a>  ))</span>
<span id="cb90-11"><a href="data-management---cross-sectional-data.html#cb90-11" tabindex="-1"></a></span>
<span id="cb90-12"><a href="data-management---cross-sectional-data.html#cb90-12" tabindex="-1"></a>females <span class="ot">&lt;-</span> females <span class="sc">%&gt;%</span></span>
<span id="cb90-13"><a href="data-management---cross-sectional-data.html#cb90-13" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Income =</span> <span class="fu">case_when</span>(</span>
<span id="cb90-14"><a href="data-management---cross-sectional-data.html#cb90-14" tabindex="-1"></a>    Age2 <span class="sc">&gt;=</span> <span class="dv">40</span> <span class="sc">~</span> <span class="fu">runif</span>(<span class="fu">n</span>(), <span class="dv">50000</span>, <span class="dv">70000</span>),  <span class="co"># 1st Gen</span></span>
<span id="cb90-15"><a href="data-management---cross-sectional-data.html#cb90-15" tabindex="-1"></a>    Age2 <span class="sc">&gt;=</span> <span class="dv">31</span> <span class="sc">&amp;</span> Age2 <span class="sc">&lt;=</span> <span class="dv">39</span> <span class="sc">~</span> <span class="fu">runif</span>(<span class="fu">n</span>(), <span class="dv">40000</span>, <span class="dv">60000</span>),  <span class="co"># 2nd Gen</span></span>
<span id="cb90-16"><a href="data-management---cross-sectional-data.html#cb90-16" tabindex="-1"></a>    Age2 <span class="sc">&gt;=</span> <span class="dv">25</span> <span class="sc">&amp;</span> Age2 <span class="sc">&lt;=</span> <span class="dv">30</span> <span class="sc">~</span> <span class="fu">runif</span>(<span class="fu">n</span>(), <span class="dv">30000</span>, <span class="dv">50000</span>),  <span class="co"># 3rd Gen</span></span>
<span id="cb90-17"><a href="data-management---cross-sectional-data.html#cb90-17" tabindex="-1"></a>    Age2 <span class="sc">&lt;=</span> <span class="dv">24</span> <span class="sc">~</span> <span class="fu">runif</span>(<span class="fu">n</span>(), <span class="dv">20000</span>, <span class="dv">40000</span>)  <span class="co"># 4th Gen</span></span>
<span id="cb90-18"><a href="data-management---cross-sectional-data.html#cb90-18" tabindex="-1"></a>  ))</span></code></pre></div></li>
<li><p>Combine datasets</p>
<p>So, I taught you how to merge the datasets. You can do that as well, however, it is important to determine which came from the males, which came from the females so, you need to create a new column in the males and the females that would include the Gender.</p>
<p>I also show a different way of merging datasets. I use <code>bind_rows</code> since males and females have the same columns. However, if you view the <code>combined</code> dataset, you will notice that the females will appear after the males. This is fine.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="data-management---cross-sectional-data.html#cb91-1" tabindex="-1"></a><span class="co"># Ensure column names match and add a Gender column</span></span>
<span id="cb91-2"><a href="data-management---cross-sectional-data.html#cb91-2" tabindex="-1"></a>males <span class="ot">&lt;-</span> males <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Gender =</span> <span class="st">&quot;Male&quot;</span>)</span>
<span id="cb91-3"><a href="data-management---cross-sectional-data.html#cb91-3" tabindex="-1"></a>females <span class="ot">&lt;-</span> females <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Gender =</span> <span class="st">&quot;Female&quot;</span>)</span>
<span id="cb91-4"><a href="data-management---cross-sectional-data.html#cb91-4" tabindex="-1"></a></span>
<span id="cb91-5"><a href="data-management---cross-sectional-data.html#cb91-5" tabindex="-1"></a><span class="co"># Combine the datasets</span></span>
<span id="cb91-6"><a href="data-management---cross-sectional-data.html#cb91-6" tabindex="-1"></a>combined <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(males, females)</span>
<span id="cb91-7"><a href="data-management---cross-sectional-data.html#cb91-7" tabindex="-1"></a></span>
<span id="cb91-8"><a href="data-management---cross-sectional-data.html#cb91-8" tabindex="-1"></a><span class="co"># View the combined dataset</span></span>
<span id="cb91-9"><a href="data-management---cross-sectional-data.html#cb91-9" tabindex="-1"></a><span class="fu">View</span>(combined)</span></code></pre></div></li>
</ol>
<p>Calculate the Income Difference</p>
<p>I use the <code>group_by</code> function and the <code>summarise</code> function. I got the Mean and the Median. Later on, I will discuss the difference between getting the mean and the median or when best to use the mean or the median.</p>
<pre><code>## # A tibble: 2 × 3
##   Gender Mean_Income Median_Income
##   &lt;chr&gt;        &lt;dbl&gt;         &lt;dbl&gt;
## 1 Female      36858.        36414.
## 2 Male        37907.        37246.</code></pre>
<pre><code>## The gender with the higher mean income is: Male</code></pre>
<pre><code>## The gender with the higher median income is: Male</code></pre>
<ol start="11" style="list-style-type: decimal">
<li>Now that we have the combined dataset, simply save it as a CSV file and you are done with the practical.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="basic-introduction-to-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-management---time-series-and-panel-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["LBOMETR_Course_Book.pdf", "LBOMETR_Course_Book.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"depth": 4
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
