<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10 Descriptive Statistics | LBOMETR Course Book</title>
  <meta name="description" content="An introduction to the LBOMETR Course Book." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="10 Descriptive Statistics | LBOMETR Course Book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An introduction to the LBOMETR Course Book." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10 Descriptive Statistics | LBOMETR Course Book" />
  
  <meta name="twitter:description" content="An introduction to the LBOMETR Course Book." />
  

<meta name="author" content="Jem Marie M. Nario" />


<meta name="date" content="2026-01-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="advanced-visualizations.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<h1>LBOMETR Course Book</h1>
<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#about-me"><i class="fa fa-check"></i><b>1.1</b> About Me</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i><b>2</b> Syllabus</a>
<ul>
<li class="chapter" data-level="2.1" data-path="syllabus.html"><a href="syllabus.html#general-course-description"><i class="fa fa-check"></i><b>2.1</b> General Course Description</a></li>
<li class="chapter" data-level="2.2" data-path="syllabus.html"><a href="syllabus.html#specific-course-description"><i class="fa fa-check"></i><b>2.2</b> Specific Course Description</a></li>
<li class="chapter" data-level="2.3" data-path="syllabus.html"><a href="syllabus.html#final-course-outputs"><i class="fa fa-check"></i><b>2.3</b> Final Course Outputs</a></li>
<li class="chapter" data-level="2.4" data-path="syllabus.html"><a href="syllabus.html#generative-ai-use-policy"><i class="fa fa-check"></i><b>2.4</b> Generative AI-Use Policy</a></li>
<li class="chapter" data-level="2.5" data-path="syllabus.html"><a href="syllabus.html#classroom-policies"><i class="fa fa-check"></i><b>2.5</b> Classroom Policies</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="syllabus.html"><a href="syllabus.html#excused-absences-policy"><i class="fa fa-check"></i><b>2.5.1</b> EXCUSED ABSENCES POLICY:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="course-assessments.html"><a href="course-assessments.html"><i class="fa fa-check"></i><b>3</b> Course Assessments</a>
<ul>
<li class="chapter" data-level="3.1" data-path="course-assessments.html"><a href="course-assessments.html#short-quizzes"><i class="fa fa-check"></i><b>3.1</b> Short Quizzes</a></li>
<li class="chapter" data-level="3.2" data-path="course-assessments.html"><a href="course-assessments.html#problem-sets-1-and-2"><i class="fa fa-check"></i><b>3.2</b> Problem Sets (1 and 2)</a></li>
<li class="chapter" data-level="3.3" data-path="course-assessments.html"><a href="course-assessments.html#data-storytelling"><i class="fa fa-check"></i><b>3.3</b> Data Storytelling</a></li>
<li class="chapter" data-level="3.4" data-path="course-assessments.html"><a href="course-assessments.html#data-story-archive"><i class="fa fa-check"></i><b>3.4</b> Data Story Archive</a></li>
<li class="chapter" data-level="3.5" data-path="course-assessments.html"><a href="course-assessments.html#participation"><i class="fa fa-check"></i><b>3.5</b> Participation</a></li>
<li class="chapter" data-level="3.6" data-path="course-assessments.html"><a href="course-assessments.html#grading-system"><i class="fa fa-check"></i><b>3.6</b> Grading System</a></li>
<li class="chapter" data-level="3.7" data-path="course-assessments.html"><a href="course-assessments.html#grading-scale"><i class="fa fa-check"></i><b>3.7</b> Grading Scale</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="problem-sets.html"><a href="problem-sets.html"><i class="fa fa-check"></i><b>4</b> Problem Sets</a>
<ul>
<li class="chapter" data-level="4.1" data-path="problem-sets.html"><a href="problem-sets.html#introduction-1"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="problem-sets.html"><a href="problem-sets.html#assigned-topics-list-general-and-specific"><i class="fa fa-check"></i><b>4.2</b> Assigned Topics List (General and Specific)</a></li>
<li class="chapter" data-level="4.3" data-path="problem-sets.html"><a href="problem-sets.html#problem-set-1---data-management-to-descriptive-statistics-and-conceptual-endogeneity"><i class="fa fa-check"></i><b>4.3</b> Problem Set 1 - Data Management to Descriptive Statistics and Conceptual Endogeneity</a></li>
<li class="chapter" data-level="4.4" data-path="problem-sets.html"><a href="problem-sets.html#problem-set-2---testable-hypotheses-ols-diagnostics-robustness"><i class="fa fa-check"></i><b>4.4</b> Problem Set 2 - Testable Hypotheses, OLS, Diagnostics, Robustness</a></li>
<li class="chapter" data-level="4.5" data-path="problem-sets.html"><a href="problem-sets.html#reminders"><i class="fa fa-check"></i><b>4.5</b> Reminders:</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html"><i class="fa fa-check"></i><b>5</b> Basic Introduction to R</a>
<ul>
<li class="chapter" data-level="5.1" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#session-information"><i class="fa fa-check"></i><b>5.1</b> Session Information</a></li>
<li class="chapter" data-level="5.2" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#preliminaries"><i class="fa fa-check"></i><b>5.2</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#understanding-the-rstudio-screen"><i class="fa fa-check"></i><b>5.2.1</b> Understanding the RStudio Screen</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#packages"><i class="fa fa-check"></i><b>5.3</b> Packages</a></li>
<li class="chapter" data-level="5.4" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#setting-up-the-working-directory"><i class="fa fa-check"></i><b>5.4</b> Setting up the Working Directory</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#what-is-a-working-directory"><i class="fa fa-check"></i><b>5.4.1</b> What is a Working Directory?</a></li>
<li class="chapter" data-level="5.4.2" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#required-folder-structure"><i class="fa fa-check"></i><b>5.4.2</b> Required Folder Structure</a></li>
<li class="chapter" data-level="5.4.3" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#setting-the-working-directory-in-rstudio"><i class="fa fa-check"></i><b>5.4.3</b> Setting the Working Directory in RStudio</a></li>
<li class="chapter" data-level="5.4.4" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#setting-the-working-directory-using-code"><i class="fa fa-check"></i><b>5.4.4</b> Setting the Working Directory Using Code</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#cleaning-the-environment-do-this-regularly"><i class="fa fa-check"></i><b>5.5</b> Cleaning the Environment (Do This Regularly)</a></li>
<li class="chapter" data-level="5.6" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#quarto-markdown"><i class="fa fa-check"></i><b>5.6</b> Quarto Markdown</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#installing-quarto-in-r"><i class="fa fa-check"></i><b>5.6.1</b> Installing Quarto in R</a></li>
<li class="chapter" data-level="5.6.2" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#starting-a-quarto-document"><i class="fa fa-check"></i><b>5.6.2</b> Starting a Quarto Document</a></li>
<li class="chapter" data-level="5.6.3" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#yaml-header-use"><i class="fa fa-check"></i><b>5.6.3</b> YAML Header Use</a></li>
<li class="chapter" data-level="5.6.4" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#quarto-key-features"><i class="fa fa-check"></i><b>5.6.4</b> Quarto Key Features</a></li>
<li class="chapter" data-level="5.6.5" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#quarto-markdown-shortcuts"><i class="fa fa-check"></i><b>5.6.5</b> Quarto Markdown Shortcuts</a></li>
<li class="chapter" data-level="5.6.6" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#rendering-a-quarto-document"><i class="fa fa-check"></i><b>5.6.6</b> Rendering a Quarto Document</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#working-directories-and-file-management"><i class="fa fa-check"></i><b>5.7</b> Working Directories and File Management</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#file-naming-convention-mandatory"><i class="fa fa-check"></i><b>5.7.1</b> File Naming Convention (Mandatory)</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="basic-introduction-to-r.html"><a href="basic-introduction-to-r.html#mini-exercise-first-quarto-render-mandatory-per-individual"><i class="fa fa-check"></i><b>5.8</b> Mini-Exercise: First Quarto Render (Mandatory per Individual)</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html"><i class="fa fa-check"></i><b>6</b> Data Management - Cross-Sectional Data</a>
<ul>
<li class="chapter" data-level="6.1" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#where-to-get-data"><i class="fa fa-check"></i><b>6.1</b> Where to Get Data?</a></li>
<li class="chapter" data-level="6.2" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#preliminaries-1"><i class="fa fa-check"></i><b>6.2</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#packages-1"><i class="fa fa-check"></i><b>6.2.1</b> Packages</a></li>
<li class="chapter" data-level="6.2.2" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#clean-everything"><i class="fa fa-check"></i><b>6.2.2</b> Clean Everything</a></li>
<li class="chapter" data-level="6.2.3" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#importing-the-datasets"><i class="fa fa-check"></i><b>6.2.3</b> Importing the Datasets</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#data-cleaning"><i class="fa fa-check"></i><b>6.3</b> Data Cleaning</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#renaming-the-variables"><i class="fa fa-check"></i><b>6.3.1</b> Renaming the Variables</a></li>
<li class="chapter" data-level="6.3.2" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#sorting-variables"><i class="fa fa-check"></i><b>6.3.2</b> Sorting Variables</a></li>
<li class="chapter" data-level="6.3.3" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#pipe-operator"><i class="fa fa-check"></i><b>6.3.3</b> Pipe Operator</a></li>
<li class="chapter" data-level="6.3.4" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#adding-columns"><i class="fa fa-check"></i><b>6.3.4</b> Adding columns</a></li>
<li class="chapter" data-level="6.3.5" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#transforming-values"><i class="fa fa-check"></i><b>6.3.5</b> Transforming Values</a></li>
<li class="chapter" data-level="6.3.6" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#categorizing-into-groups"><i class="fa fa-check"></i><b>6.3.6</b> Categorizing into groups</a></li>
<li class="chapter" data-level="6.3.7" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#summarizing"><i class="fa fa-check"></i><b>6.3.7</b> Summarizing</a></li>
<li class="chapter" data-level="6.3.8" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#merging-datasets"><i class="fa fa-check"></i><b>6.3.8</b> Merging datasets</a></li>
<li class="chapter" data-level="6.3.9" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#splitting-datasets"><i class="fa fa-check"></i><b>6.3.9</b> Splitting datasets</a></li>
<li class="chapter" data-level="6.3.10" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#reshaping-datasets"><i class="fa fa-check"></i><b>6.3.10</b> Reshaping Datasets</a></li>
<li class="chapter" data-level="6.3.11" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#missing-values"><i class="fa fa-check"></i><b>6.3.11</b> Missing Values</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="data-management---cross-sectional-data.html"><a href="data-management---cross-sectional-data.html#closing"><i class="fa fa-check"></i><b>6.4</b> Closing</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html"><i class="fa fa-check"></i><b>7</b> Data Management - Time Series and Panel Data</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#time-series-data"><i class="fa fa-check"></i><b>7.1</b> Time Series Data</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#preliminaries-2"><i class="fa fa-check"></i><b>7.1.1</b> Preliminaries</a></li>
<li class="chapter" data-level="7.1.2" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#create-a-simple-date-dataset"><i class="fa fa-check"></i><b>7.1.2</b> Create a Simple Date Dataset</a></li>
<li class="chapter" data-level="7.1.3" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#converting-character-dates-to-date-format"><i class="fa fa-check"></i><b>7.1.3</b> Converting Character Dates to Date Format</a></li>
<li class="chapter" data-level="7.1.4" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#calculate-age"><i class="fa fa-check"></i><b>7.1.4</b> Calculate Age:</a></li>
<li class="chapter" data-level="7.1.5" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#using-time-series-data"><i class="fa fa-check"></i><b>7.1.5</b> Using Time Series Data</a></li>
<li class="chapter" data-level="7.1.6" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#convert-to-date-format"><i class="fa fa-check"></i><b>7.1.6</b> Convert to Date Format</a></li>
<li class="chapter" data-level="7.1.7" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#aggregate-data"><i class="fa fa-check"></i><b>7.1.7</b> Aggregate Data</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#panel-data"><i class="fa fa-check"></i><b>7.2</b> Panel Data</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#sorting-panel-data"><i class="fa fa-check"></i><b>7.2.1</b> Sorting Panel Data</a></li>
<li class="chapter" data-level="7.2.2" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#checking-panel-balance"><i class="fa fa-check"></i><b>7.2.2</b> Checking Panel Balance</a></li>
<li class="chapter" data-level="7.2.3" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#creating-lagged-variables"><i class="fa fa-check"></i><b>7.2.3</b> Creating Lagged Variables</a></li>
<li class="chapter" data-level="7.2.4" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#missing-data-in-panels"><i class="fa fa-check"></i><b>7.2.4</b> Missing Data in Panels</a></li>
<li class="chapter" data-level="7.2.5" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#creating-growth-rates"><i class="fa fa-check"></i><b>7.2.5</b> Creating Growth Rates</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="data-management---time-series-and-panel-data.html"><a href="data-management---time-series-and-panel-data.html#closing-1"><i class="fa fa-check"></i><b>7.3</b> Closing</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html"><i class="fa fa-check"></i><b>8</b> Visualizations using ggplot2</a>
<ul>
<li class="chapter" data-level="8.1" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#preliminaries-3"><i class="fa fa-check"></i><b>8.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#load-the-dataset"><i class="fa fa-check"></i><b>8.1.1</b> Load the dataset</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#pre-plotting-check"><i class="fa fa-check"></i><b>8.2</b> Pre-plotting Check</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#template"><i class="fa fa-check"></i><b>8.2.1</b> Template</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#visualizing-data-using-geom"><i class="fa fa-check"></i><b>8.3</b> Visualizing Data using <code>geom</code></a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#scatterplots"><i class="fa fa-check"></i><b>8.3.1</b> Scatterplots</a></li>
<li class="chapter" data-level="8.3.2" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#boxplots"><i class="fa fa-check"></i><b>8.3.2</b> Boxplots</a></li>
<li class="chapter" data-level="8.3.3" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#bar-plots"><i class="fa fa-check"></i><b>8.3.3</b> Bar plots</a></li>
<li class="chapter" data-level="8.3.4" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#faceting"><i class="fa fa-check"></i><b>8.3.4</b> Faceting</a></li>
<li class="chapter" data-level="8.3.5" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#pie-chart"><i class="fa fa-check"></i><b>8.3.5</b> Pie Chart</a></li>
<li class="chapter" data-level="8.3.6" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#histogram"><i class="fa fa-check"></i><b>8.3.6</b> Histogram</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#visualizing-time-series-data"><i class="fa fa-check"></i><b>8.4</b> Visualizing Time Series Data</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#save-graphs-using-ggplot2"><i class="fa fa-check"></i><b>8.4.1</b> Save Graphs using ggplot2</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#closing-2"><i class="fa fa-check"></i><b>8.5</b> Closing</a></li>
<li class="chapter" data-level="8.6" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#visual-baseR"><i class="fa fa-check"></i><b>8.6</b> Visualizations using Base R</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#scatterplots-1"><i class="fa fa-check"></i><b>8.6.1</b> Scatterplots</a></li>
<li class="chapter" data-level="8.6.2" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#boxplots-1"><i class="fa fa-check"></i><b>8.6.2</b> Boxplots</a></li>
<li class="chapter" data-level="8.6.3" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#bar-plots-1"><i class="fa fa-check"></i><b>8.6.3</b> Bar Plots</a></li>
<li class="chapter" data-level="8.6.4" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#faceting-1"><i class="fa fa-check"></i><b>8.6.4</b> Faceting</a></li>
<li class="chapter" data-level="8.6.5" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#pie-chart-1"><i class="fa fa-check"></i><b>8.6.5</b> Pie Chart</a></li>
<li class="chapter" data-level="8.6.6" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#histogram-1"><i class="fa fa-check"></i><b>8.6.6</b> Histogram</a></li>
<li class="chapter" data-level="8.6.7" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#time-series"><i class="fa fa-check"></i><b>8.6.7</b> Time Series</a></li>
<li class="chapter" data-level="8.6.8" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#save-graphs-using-base-r"><i class="fa fa-check"></i><b>8.6.8</b> Save Graphs using Base R</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="visualizations-using-ggplot2.html"><a href="visualizations-using-ggplot2.html#closing-3"><i class="fa fa-check"></i><b>8.7</b> Closing</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html"><i class="fa fa-check"></i><b>9</b> Advanced Visualizations</a>
<ul>
<li class="chapter" data-level="9.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#preliminaries-4"><i class="fa fa-check"></i><b>9.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#install-packages"><i class="fa fa-check"></i><b>9.1.1</b> Install Packages</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-visualizations"><i class="fa fa-check"></i><b>9.2</b> Animated Visualizations</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-bar-chart"><i class="fa fa-check"></i><b>9.2.1</b> Animated Bar Chart</a></li>
<li class="chapter" data-level="9.2.2" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-scatter-plot"><i class="fa fa-check"></i><b>9.2.2</b> Animated Scatter Plot</a></li>
<li class="chapter" data-level="9.2.3" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-faceted-scatter-plot"><i class="fa fa-check"></i><b>9.2.3</b> Animated Faceted Scatter Plot</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-time-series"><i class="fa fa-check"></i><b>9.3</b> Animated Time Series</a></li>
<li class="chapter" data-level="9.4" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-faceted-time-series"><i class="fa fa-check"></i><b>9.4</b> Animated Faceted Time Series</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#saving-in-quarto"><i class="fa fa-check"></i><b>9.4.1</b> Saving in Quarto</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#maps"><i class="fa fa-check"></i><b>9.5</b> Maps</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#where-to-get-shapefiles"><i class="fa fa-check"></i><b>9.5.1</b> Where to get shapefiles?</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#static-maps"><i class="fa fa-check"></i><b>9.6</b> Static Maps</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#fetching-gdp-data-from-wdi"><i class="fa fa-check"></i><b>9.6.1</b> Fetching GDP Data from WDI</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#philippine-regional-map"><i class="fa fa-check"></i><b>9.7</b> Philippine Regional Map</a></li>
<li class="chapter" data-level="9.8" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#animated-map"><i class="fa fa-check"></i><b>9.8</b> Animated Map</a></li>
<li class="chapter" data-level="9.9" data-path="advanced-visualizations.html"><a href="advanced-visualizations.html#practical-advanced-visualizations"><i class="fa fa-check"></i><b>9.9</b> Practical: Advanced Visualizations</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>10</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="10.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#preliminaries-5"><i class="fa fa-check"></i><b>10.1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#install-packages-1"><i class="fa fa-check"></i><b>10.1.1</b> Install Packages</a></li>
<li class="chapter" data-level="10.1.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#load-the-dataset-1"><i class="fa fa-check"></i><b>10.1.2</b> Load the dataset</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#frequency-table"><i class="fa fa-check"></i><b>10.2</b> Frequency Table</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#male"><i class="fa fa-check"></i><b>10.2.1</b> Male</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#histogram-2"><i class="fa fa-check"></i><b>10.3</b> Histogram</a></li>
<li class="chapter" data-level="10.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summary-table"><i class="fa fa-check"></i><b>10.4</b> Summary Table</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summary-table-using-stargazer"><i class="fa fa-check"></i><b>10.4.1</b> Summary Table using Stargazer</a></li>
<li class="chapter" data-level="10.4.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summary-table-with-grouping-and-stargazer"><i class="fa fa-check"></i><b>10.4.2</b> Summary Table with Grouping and Stargazer</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#control-variables"><i class="fa fa-check"></i><b>10.5</b> Control Variables</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#what-is-a-control-variable"><i class="fa fa-check"></i><b>10.5.1</b> What is a Control Variable?</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#confounding-variables"><i class="fa fa-check"></i><b>10.6</b> Confounding Variables</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#what-is-a-confounding-variable"><i class="fa fa-check"></i><b>10.6.1</b> What is a Confounding Variable?</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#difference-between-control-variables-and-confounding-variables"><i class="fa fa-check"></i><b>10.7</b> Difference between Control Variables and Confounding Variables</a></li>
<li class="chapter" data-level="10.8" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#descriptive-statistics-of-control-and-confounding-variables"><i class="fa fa-check"></i><b>10.8</b> Descriptive Statistics of Control and Confounding Variables</a></li>
<li class="chapter" data-level="10.9" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#descriptive-statistics-of-categoricalcharacter-variables"><i class="fa fa-check"></i><b>10.9</b> Descriptive Statistics of Categorical/Character Variables</a></li>
<li class="chapter" data-level="10.10" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#importance-of-descriptive-statistics"><i class="fa fa-check"></i><b>10.10</b> Importance of Descriptive Statistics:</a>
<ul>
<li class="chapter" data-level="10.10.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#key-components-of-descriptive-statistics"><i class="fa fa-check"></i><b>10.10.1</b> <strong>Key Components of Descriptive Statistics</strong></a></li>
<li class="chapter" data-level="10.10.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#when-to-use-mean-or-median"><i class="fa fa-check"></i><b>10.10.2</b> <strong>When to Use Mean or Median</strong></a></li>
<li class="chapter" data-level="10.10.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#how-descriptive-statistics-help-in-regression"><i class="fa fa-check"></i><b>10.10.3</b> How Descriptive Statistics Help in Regression</a></li>
<li class="chapter" data-level="10.10.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#limitations"><i class="fa fa-check"></i><b>10.10.4</b> <strong>Limitations</strong></a></li>
</ul></li>
<li class="chapter" data-level="10.11" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#closing-4"><i class="fa fa-check"></i><b>10.11</b> Closing</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">LBOMETR Course Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="descriptive-statistics" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">10</span> Descriptive Statistics<a href="descriptive-statistics.html#descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>For this section, we will make use of <code>Ch6PRactice.RData</code>. Since the file is in RData format, we will only need to load it in R.</p>
<div id="preliminaries-5" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Preliminaries<a href="descriptive-statistics.html#preliminaries-5" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="install-packages-1" class="section level3 hasAnchor" number="10.1.1">
<h3><span class="header-section-number">10.1.1</span> Install Packages<a href="descriptive-statistics.html#install-packages-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We install and load the <code>psych</code> , <code>stargazer, kableExtra</code> and <code>gtsummary</code> packages and load <code>tidyverse</code> package.</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="descriptive-statistics.html#cb288-1" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span>(<span class="st">&quot;psych&quot;</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[,<span class="st">&quot;Package&quot;</span>])) <span class="fu">install.packages</span>(<span class="st">&quot;psych&quot;</span>)</span>
<span id="cb288-2"><a href="descriptive-statistics.html#cb288-2" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span>(<span class="st">&quot;gtsummary&quot;</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[,<span class="st">&quot;Package&quot;</span>])) <span class="fu">install.packages</span>(<span class="st">&quot;gtsummary&quot;</span>)</span>
<span id="cb288-3"><a href="descriptive-statistics.html#cb288-3" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span>(<span class="st">&quot;stargazer&quot;</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[,<span class="st">&quot;Package&quot;</span>])) <span class="fu">install.packages</span>(<span class="st">&quot;stargazer&quot;</span>)</span>
<span id="cb288-4"><a href="descriptive-statistics.html#cb288-4" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span>(<span class="st">&quot;kableExtra&quot;</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[,<span class="st">&quot;Package&quot;</span>])) <span class="fu">install.packages</span>(<span class="st">&quot;kableExtra&quot;</span>)</span>
<span id="cb288-5"><a href="descriptive-statistics.html#cb288-5" tabindex="-1"></a></span>
<span id="cb288-6"><a href="descriptive-statistics.html#cb288-6" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb288-7"><a href="descriptive-statistics.html#cb288-7" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb288-8"><a href="descriptive-statistics.html#cb288-8" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb288-9"><a href="descriptive-statistics.html#cb288-9" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb288-10"><a href="descriptive-statistics.html#cb288-10" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code></pre></div>
</div>
<div id="load-the-dataset-1" class="section level3 hasAnchor" number="10.1.2">
<h3><span class="header-section-number">10.1.2</span> Load the dataset<a href="descriptive-statistics.html#load-the-dataset-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="descriptive-statistics.html#cb289-1" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span>
<span id="cb289-2"><a href="descriptive-statistics.html#cb289-2" tabindex="-1"></a><span class="fu">gc</span>()</span></code></pre></div>
<pre><code>##            used  (Mb) gc trigger   (Mb)  max used   (Mb)
## Ncells  4136156 220.9    6945420  371.0   6945420  371.0
## Vcells 35464329 270.6  142307337 1085.8 222355213 1696.5</code></pre>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="descriptive-statistics.html#cb291-1" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;Ch6Practice.RData&quot;</span>)</span></code></pre></div>
<p>We subset the data:</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="descriptive-statistics.html#cb292-1" tabindex="-1"></a><span class="co"># Create a subset of the dataset with only female respondents </span></span>
<span id="cb292-2"><a href="descriptive-statistics.html#cb292-2" tabindex="-1"></a>Dataset_CP_f <span class="ot">&lt;-</span> Dataset_CP <span class="sc">%&gt;%</span> <span class="fu">filter</span>(HH2a_Sex <span class="sc">==</span> <span class="st">&quot;Female&quot;</span>)  </span>
<span id="cb292-3"><a href="descriptive-statistics.html#cb292-3" tabindex="-1"></a><span class="co"># Create a subset of the dataset with only male respondents</span></span>
<span id="cb292-4"><a href="descriptive-statistics.html#cb292-4" tabindex="-1"></a>Dataset_CP_m <span class="ot">&lt;-</span> Dataset_CP <span class="sc">%&gt;%</span> <span class="fu">filter</span>(HH2a_Sex <span class="sc">==</span> <span class="st">&quot;Male&quot;</span>)</span>
<span id="cb292-5"><a href="descriptive-statistics.html#cb292-5" tabindex="-1"></a><span class="fu">str</span>(Dataset_CP_m)</span></code></pre></div>
<pre><code>## tibble [1,723 × 49] (S3: tbl_df/tbl/data.frame)
##  $ Country                     : Factor w/ 34 levels &quot;Austria&quot;,&quot;Belgium&quot;,..: 20 25 3 8 12 16 7 21 6 6 ...
##  $ ID                          : chr [1:1723] &quot;NL5063519&quot; &quot;SI1042916&quot; &quot;BG1396625&quot; &quot;EE1261010&quot; ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Unique respondent ID&quot;
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;A60&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 9
##  $ HH1_Num_People              : num [1:1723] 2 3 2 2 2 2 1 2 2 1 ...
##  $ HH2a_Sex                    : Factor w/ 2 levels &quot;Male&quot;,&quot;Female&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ HH2b_Age                    : num [1:1723] 63 63 89 52 81 54 59 76 70 53 ...
##  $ HH2d_EmploymentSituation    : Factor w/ 10 levels &quot;At work as employee or employer/self-employed&quot;,..: 7 1 7 7 7 6 1 7 7 1 ...
##  $ Q1_PaidJob                  : Factor w/ 4 levels &quot;Yes&quot;,&quot;No&quot;,&quot;Don&#39;t Know&quot;,..: 1 NA 1 1 1 1 NA 1 1 NA ...
##  $ Q2_Empoyment                : Factor w/ 6 levels &quot;Self-employed without employees&quot;,..: NA 3 NA NA NA NA 3 NA NA 3 ...
##  $ Q3_Contract                 : Factor w/ 9 levels &quot;On an unlimited permanent contract&quot;,..: NA 1 NA NA NA NA 1 NA NA 1 ...
##  $ Q4_Occupation               : Factor w/ 13 levels &quot;Armed forces&quot;,..: NA 4 NA NA NA NA 6 NA NA 6 ...
##  $ Q7_HoursWeekWork            : num [1:1723] NA 35 NA NA NA NA 37 NA NA 25 ...
##  $ Q7a_AdditionalJob           : Factor w/ 4 levels &quot;Yes&quot;,&quot;No&quot;,&quot;Don&#39;t know&quot;,..: NA 2 NA NA NA NA 2 NA NA 2 ...
##  $ Q7b_HoursWeekWeekAddJob     : num [1:1723] NA NA NA NA NA NA NA NA NA NA ...
##  $ Q7c_Work                    : Factor w/ 4 levels &quot;Yes&quot;,&quot;No&quot;,&quot;Don&#39;t Know&quot;,..: 2 NA 2 1 2 2 NA 2 2 NA ...
##  $ Q8_HoursWeekWorkPref        : num [1:1723] 0 30 0 40 0 20 30 NA 40 38 ...
##  $ Q9_HoursWeekWorkPartner     : num [1:1723] NA NA NA 41 NA 30 NA NA NA NA ...
##  $ Q10_HoursWeekWorkPartnerPref: num [1:1723] 0 30 0 30 0 40 NA NA 35 NA ...
##  $ Q17_Rooms                   : num [1:1723] 6 3 1 NA 3 4 2 3 3 1 ...
##  $ Q18_Tenancy                 : Factor w/ 8 levels &quot;Own without mortgage&quot;,..: 2 3 1 1 5 1 1 1 4 4 ...
##  $ Q19a_ShortageSpace          : num [1:1723] 0 0 0 0 0 0 1 0 0 1 ...
##  $ Q19b_Rot                    : num [1:1723] 0 0 0 0 0 0 0 1 0 0 ...
##  $ Q19c_Leaks                  : num [1:1723] 0 0 0 0 0 1 0 1 0 0 ...
##  $ Q19d_NoFlusingToilet        : num [1:1723] 0 0 0 0 0 0 0 0 0 0 ...
##  $ Q19e_NoBathShower           : num [1:1723] 0 0 0 0 0 0 0 0 0 0 ...
##  $ Q19f_NoOutside              : num [1:1723] 0 0 0 0 0 1 0 0 0 0 ...
##  $ Q20_LeaveAccomodation_NoAff : Factor w/ 6 levels &quot;Very likely&quot;,..: 4 3 4 4 4 4 4 4 4 4 ...
##  $ Q24_Trust                   : Factor w/ 12 levels &quot;1 - you can&#39;t be too careful&quot;,..: 8 6 1 9 5 10 6 2 3 4 ...
##  $ Q25a_TensionClass           : Factor w/ 5 levels &quot;A lot of tension&quot;,..: 2 2 2 2 1 1 2 1 3 4 ...
##  $ Q25b_TensionWork            : Factor w/ 5 levels &quot;A lot of tension&quot;,..: 2 2 4 2 1 1 2 1 3 3 ...
##  $ Q25c_TensionSex             : Factor w/ 5 levels &quot;A lot of tension&quot;,..: 3 3 2 3 1 1 3 2 2 2 ...
##  $ Q25d_TensionsAge            : hvn_lbl_ [1:1723]  3,  3,  2, 98,  1,  1,  2,  2,  3,  2,  2, 98,  3,  1,  2,  3,  1,  3,  2,  2,  2,  3,  3,  2,  2,  2,  2,  3,  3...
##    ..@ label      : chr &quot;Q25d Old people and young people / How much tension is there in this country?&quot;
##    ..@ na_values  : num [1:2] 98 99
##    ..@ format.spss: chr &quot;F8.0&quot;
##    ..@ labels     : Named num [1:5] 1 2 3 98 99
##    .. ..- attr(*, &quot;names&quot;)= chr [1:5] &quot;A lot of  tension&quot; &quot;Some tension&quot; &quot;No tension&quot; &quot;(Don’t know)&quot; ...
##  $ Q25e_TensionRace            : Factor w/ 5 levels &quot;A lot of tension&quot;,..: 1 2 4 2 1 1 2 2 2 1 ...
##  $ Q25f_TensionReligion        : Factor w/ 5 levels &quot;A lot of tension&quot;,..: 1 2 4 3 2 1 2 2 2 1 ...
##  $ Q25g_TensionSexOrient       : Factor w/ 5 levels &quot;A lot of tension&quot;,..: 2 3 4 1 1 1 2 3 3 4 ...
##  $ Q37a_HoursWeekChildren      : num [1:1723] NA 5 NA 4 NA NA NA NA NA NA ...
##  $ Q37b_HoursWeekHousework     : num [1:1723] 14 NA NA 4 6 NA 7 12 3 5 ...
##  $ Q37c_HoursWeekElderly       : num [1:1723] 3 NA NA NA NA NA NA NA NA NA ...
##  $ Q48_Education               : Factor w/ 472 levels &quot;1010&quot;,&quot;1011&quot;,..: 306 361 44 111 174 226 91 312 78 76 ...
##  $ Q49_Area                    : Factor w/ 6 levels &quot;The open countryside&quot;,..: 3 3 4 2 2 2 4 2 2 4 ...
##  $ Q50a_NeighbourhoodNoise     : Factor w/ 5 levels &quot;Major problems&quot;,..: 3 3 3 3 3 3 3 3 3 2 ...
##  $ Q50b_NeighbourhoodAir       : Factor w/ 5 levels &quot;Major problems&quot;,..: 3 3 3 3 3 3 3 3 2 4 ...
##  $ Q50c_NeighbourhoodWater     : Factor w/ 5 levels &quot;Major problems&quot;,..: 3 3 3 2 3 1 3 3 3 4 ...
##  $ Q50d_NeighbourhoodCrime     : Factor w/ 5 levels &quot;Major problems&quot;,..: 3 3 2 3 3 3 2 3 3 1 ...
##  $ Q50e_NeighbourhoodLitter    : Factor w/ 5 levels &quot;Major problems&quot;,..: 3 3 2 2 3 3 3 3 3 1 ...
##  $ Q50f_NeighbourhoodTraffic   : Factor w/ 5 levels &quot;Major problems&quot;,..: 3 2 4 3 3 3 3 3 3 4 ...
##  $ Q51a_AccServicesPost        : Factor w/ 7 levels &quot;With great difficulty&quot;,..: 3 3 5 3 3 1 2 2 3 4 ...
##  $ Q51b_AccServicesBank        : Factor w/ 7 levels &quot;With great difficulty&quot;,..: 3 3 5 3 3 1 4 5 3 4 ...
##  $ Q53c_QualityPublicTransport : Factor w/ 12 levels &quot;1 - very poor quality&quot;,..: 7 6 3 8 5 2 4 11 8 7 ...
##  $ Income_PPP                  : num [1:1723] 3191 4172 478 426 887 ...</code></pre>
<blockquote>
<p><strong>Do Descriptive Statistics for Female Respondents.</strong> <strong>We compare.</strong></p>
</blockquote>
</div>
</div>
<div id="frequency-table" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Frequency Table<a href="descriptive-statistics.html#frequency-table" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Run a Frequency Table for the number of hours the respondents spend caring for children and/or grandchildren per week (variable <strong>Q37a_HoursWeekChildren</strong>). For both sex separately, report the mean and standard deviation.</p>
<div id="male" class="section level3 hasAnchor" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> Male<a href="descriptive-statistics.html#male" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Calculate the descriptive statistics for the variable <strong>Q37a_HoursWeekChildren</strong>, using the function <em>describe</em> of the package <em>psych</em>:</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="descriptive-statistics.html#cb294-1" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(Dataset_CP_m<span class="sc">$</span>Q37a_HoursWeekChildren)</span></code></pre></div>
<pre><code>##    vars   n  mean    sd median trimmed   mad min max range skew kurtosis   se
## X1    1 575 16.86 15.53     10   14.36 10.38   1 100    99 1.83     4.65 0.65</code></pre>
<p>Notice how we directly use the <em>describe</em> function on the variable <strong>Q37a_HoursWeekChildren</strong> (called with the dollar sign operator, <em>$</em>, which works as follows: <em>name_dataset$name_variable</em> - notice that to access a specific variable, some functions can use the pipe operator while others require the dollar sign operator, as in this case). Notice also how we call the function <em>describe</em>: we use the :: operator, which tells R to look for a function within a specific package as follows</p>
<p><em>name_package::name_function</em></p>
<p>You could also simply call the function by only using its name, R will then search for that specific function across all the loaded R packages. However, if more packages have functions with the same name, specifying the name of the package with the :: operator helps assuring the usage of the correct function.</p>
<p>Report the Frequency Table for the variable <strong>Q37a_HoursWeekChildren</strong>, using the function <code>tbl_summary</code> of the package <code>gtsummary</code>:</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="descriptive-statistics.html#cb296-1" tabindex="-1"></a>Dataset_CP_m <span class="sc">%&gt;%</span></span>
<span id="cb296-2"><a href="descriptive-statistics.html#cb296-2" tabindex="-1"></a>  <span class="fu">select</span>(Q37a_HoursWeekChildren) <span class="sc">%&gt;%</span></span>
<span id="cb296-3"><a href="descriptive-statistics.html#cb296-3" tabindex="-1"></a>  <span class="fu">tbl_summary</span>(</span>
<span id="cb296-4"><a href="descriptive-statistics.html#cb296-4" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="fu">list</span>(<span class="fu">all_categorical</span>() <span class="sc">~</span> <span class="st">&quot;{n} ({p}%)&quot;</span>),  <span class="co"># Show count &amp; percentage</span></span>
<span id="cb296-5"><a href="descriptive-statistics.html#cb296-5" tabindex="-1"></a>    <span class="at">missing =</span> <span class="st">&quot;no&quot;</span>  <span class="co"># Exclude missing values (set to &quot;ifany&quot; to include)</span></span>
<span id="cb296-6"><a href="descriptive-statistics.html#cb296-6" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb296-7"><a href="descriptive-statistics.html#cb296-7" tabindex="-1"></a>  <span class="fu">modify_header</span>(<span class="at">label =</span> <span class="st">&quot;**Hours per Week with Children**&quot;</span>)  <span class="co"># Customize header</span></span></code></pre></div>
<div id="ciqfwvzkno" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ciqfwvzkno table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ciqfwvzkno thead, #ciqfwvzkno tbody, #ciqfwvzkno tfoot, #ciqfwvzkno tr, #ciqfwvzkno td, #ciqfwvzkno th {
  border-style: none;
}

#ciqfwvzkno p {
  margin: 0;
  padding: 0;
}

#ciqfwvzkno .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ciqfwvzkno .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ciqfwvzkno .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ciqfwvzkno .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ciqfwvzkno .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ciqfwvzkno .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ciqfwvzkno .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ciqfwvzkno .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ciqfwvzkno .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ciqfwvzkno .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ciqfwvzkno .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ciqfwvzkno .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ciqfwvzkno .gt_spanner_row {
  border-bottom-style: hidden;
}

#ciqfwvzkno .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ciqfwvzkno .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ciqfwvzkno .gt_from_md > :first-child {
  margin-top: 0;
}

#ciqfwvzkno .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ciqfwvzkno .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ciqfwvzkno .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ciqfwvzkno .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ciqfwvzkno .gt_row_group_first td {
  border-top-width: 2px;
}

#ciqfwvzkno .gt_row_group_first th {
  border-top-width: 2px;
}

#ciqfwvzkno .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ciqfwvzkno .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ciqfwvzkno .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ciqfwvzkno .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ciqfwvzkno .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ciqfwvzkno .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ciqfwvzkno .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ciqfwvzkno .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ciqfwvzkno .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ciqfwvzkno .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ciqfwvzkno .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ciqfwvzkno .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ciqfwvzkno .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ciqfwvzkno .gt_left {
  text-align: left;
}

#ciqfwvzkno .gt_center {
  text-align: center;
}

#ciqfwvzkno .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ciqfwvzkno .gt_font_normal {
  font-weight: normal;
}

#ciqfwvzkno .gt_font_bold {
  font-weight: bold;
}

#ciqfwvzkno .gt_font_italic {
  font-style: italic;
}

#ciqfwvzkno .gt_super {
  font-size: 65%;
}

#ciqfwvzkno .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ciqfwvzkno .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ciqfwvzkno .gt_indent_1 {
  text-indent: 5px;
}

#ciqfwvzkno .gt_indent_2 {
  text-indent: 10px;
}

#ciqfwvzkno .gt_indent_3 {
  text-indent: 15px;
}

#ciqfwvzkno .gt_indent_4 {
  text-indent: 20px;
}

#ciqfwvzkno .gt_indent_5 {
  text-indent: 25px;
}

#ciqfwvzkno .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#ciqfwvzkno div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="label"><span class='gt_from_md'><strong>Hours per Week with Children</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="stat_0"><span class='gt_from_md'><strong>N = 1,723</strong></span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Q37a_HoursWeekChildren</td>
<td headers="stat_0" class="gt_row gt_center">10 (5, 24)</td></tr>
  </tbody>
  <tfoot>
    <tr class="gt_footnotes">
      <td class="gt_footnote" colspan="2"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> <span class='gt_from_md'>Median (Q1, Q3)</span></td>
    </tr>
  </tfoot>
</table>
</div>
<p>The table shows that there are 1, 723 non-missing observations for the variable, <code>Q37a_HoursWeekChildren</code></p>
<p>The median value of hours per week with children is 10 hours. (5,24) represents the interquartile range. Q1 (5): The first quartile (25th percentile) and the third quartile (75th percentile) are 5 and 24 hours respectively. This simply means that 50% of the responses lie between 5 and 24 hours per week.</p>
<p>When interpreting:</p>
<p>“The median hours per week spent with children of males is 10 hours, with half of the respondents reporting values between 5 and 24 hours. The total sample size is 1,723.”</p>
<p>Moreover, in R there are other ways to access specific elements within a dataset. Datasets are organized in rows (which represent our observations) and columns (which represent our variables). We can select a specific cell of a dataset as follows: <em>name_dataset[row, column]</em>, where <em>row</em> is the number(s) of row(s) we are interested in and <em>column</em> is either the number or the name of the column we are interested in. For instance, if we want to select the value of the variable <strong>Q37a_HoursWeekChildren</strong> for the third observation, we can use the following command</p>
<p><em>Dataset_CP[3,“Q37a_HoursWeekChildren”]</em></p>
<p>If we do not specify a value for the rows (or columns), we select all the rows (or columns) of the specified columns (or rows). For instance, the following command selects all the observations for the variable <strong>Q37a_HoursWeekChildren</strong></p>
<p><em>Dataset_CP[ ,“Q37a_HoursWeekChildren”]</em></p>
</div>
</div>
<div id="histogram-2" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Histogram<a href="descriptive-statistics.html#histogram-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Plot the histogram for the variable <strong>Q37a_HoursWeekChildren</strong></p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="descriptive-statistics.html#cb297-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Dataset_CP_m, <span class="fu">aes</span>(<span class="at">x =</span> Q37a_HoursWeekChildren)) <span class="sc">+</span>      </span>
<span id="cb297-2"><a href="descriptive-statistics.html#cb297-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">50</span>, </span>
<span id="cb297-3"><a href="descriptive-statistics.html#cb297-3" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;darkred&quot;</span>, </span>
<span id="cb297-4"><a href="descriptive-statistics.html#cb297-4" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&quot;pink&quot;</span>) <span class="sc">+</span></span>
<span id="cb297-5"><a href="descriptive-statistics.html#cb297-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span>   </span>
<span id="cb297-6"><a href="descriptive-statistics.html#cb297-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Histogram: Hours per week spent taking care of children&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;Only male respondents&quot;</span>)<span class="sc">+</span> </span>
<span id="cb297-7"><a href="descriptive-statistics.html#cb297-7" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Hours per week spent taking care of children (Question 37a)&quot;</span>) <span class="sc">+</span>   </span>
<span id="cb297-8"><a href="descriptive-statistics.html#cb297-8" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Count&quot;</span>) <span class="sc">+</span>      </span>
<span id="cb297-9"><a href="descriptive-statistics.html#cb297-9" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">&quot;darkred&quot;</span>, </span>
<span id="cb297-10"><a href="descriptive-statistics.html#cb297-10" tabindex="-1"></a>                                  <span class="at">size =</span> <span class="dv">14</span>, </span>
<span id="cb297-11"><a href="descriptive-statistics.html#cb297-11" tabindex="-1"></a>                                  <span class="at">face =</span> <span class="st">&quot;italic&quot;</span>), </span>
<span id="cb297-12"><a href="descriptive-statistics.html#cb297-12" tabindex="-1"></a>        <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">&quot;darkred&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>, <span class="at">face =</span> <span class="st">&quot;italic&quot;</span>))</span></code></pre></div>
<p><img src="LBOMETR_Course_Book_files/figure-html/unnamed-chunk-222-1.png" alt="" width="672" /></p>
<ul>
<li><p>Depending on the data, different number of bins are more or less appropriate. In this case, we indicate that we want our data to be split in 50 intervals. You could indicate a different number or you could also leave the <em>bins</em> option out of the code and let R select it (R will give a warning (not error) about the number of bins which has been selected). Each type of graph has its own set of options that can be set, use the help function to learn more about them.</p></li>
<li><p>Next, we call a pre-defined layout of the graph called <em>theme_minimal</em>. There are many pre-defined layouts and you are free to choose whichever you like the most, or even create your own layout (which is partially what we do with the last layer).</p></li>
<li><p>In the fourth layer we use <em>labs</em> in order to define the title of the graph, we add a subtitle and we specify the name of the axes. There are more options that you can define within <em>labs</em>, use <em>help(labs)</em> to find out what these are.</p></li>
<li><p>Finally, we edit the appearance of the title and subtitle using <em>theme</em> and introducing the elements <em>plot.title = element_text()</em> and <em>plot.subtitle = element_text()</em>, where we specify their <em>color</em>, <em>size</em> and <em>face</em>. With that, we are able to change the format of the title and subtitle, however, it is not always necessary. If you want to find out more options that you can specify within theme, you can use <em>help(“theme”)</em> or search in Google.</p></li>
</ul>
</div>
<div id="summary-table" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Summary Table<a href="descriptive-statistics.html#summary-table" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To summarize, we can build a table showing the mean and the standard deviation for the variable <strong>Q37a_HoursWeekChildren</strong> for the two groups, separately. To do so, we use two features:</p>
<p>First, in the menu bar of your Quarto document (on top), we click on “Table” and then select “Insert Table”. A new window will appear and ask us the number of rows and columns our table should include. Once the table has been created, we can fill in its cells with whatever we wish to present in the table.</p>
<p>Second, we use inline code, which allows us to embed directly into the text the output of an R code (you can find more information about inline coding <a href="https://r4ds.hadley.nz/quarto.html">here</a>).</p>
<p>A chunk of code, as we have seen so far, is separated from the text of our Quarto document and does not allow us to build a readable text combining words with output from R codes which in one linear sentence. So, if we want to say:<br />
<br />
The number of male respondents in our dataset is equal to</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="descriptive-statistics.html#cb298-1" tabindex="-1"></a>Dataset_CP_m <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##       n
##   &lt;int&gt;
## 1  1723</code></pre>
<p>We can clearly see that this is not ideal when using a chunk of code.<br />
<br />
To better integrate this into our text we can use inline code. To do so, in the menu bar of our Quarto document (on top), we click on “&lt;/&gt;”, then we type r and add a space and then write the line of code we would like to execute in order to include its output into the text. In our previous example, this could be done by writing as an inline code “r Dataset_CP_m %&gt;% summarize(n = n())”, as follows:<br />
<br />
The number of male respondents in our dataset is equal to 1723</p>
<p>This could be useful, for instance, if we wish to present some properties of the data without us manually copy-pasting the numbers from the console to the text. At the same time, we can use this to populate our table, as we indeed do below.</p>
<p><strong>Note:</strong></p>
<p>In a Quarto document, you can run the code which is included in a chunk of code with the green play button. This allows you to execute and visualize the output of that specific command. Unfortunately, inline codes do not have the same option. Inline codes will be executed only when the Quarto document is rendered. This means that you cannot directly see the result of inline codes before you render your Quarto document nor you can verify if that code is correct (and if it is not, the rendering will not work).</p>
<p>To overcome this issue, you can copy-paste the code of your inline code into the Console and run it from there. This will allow you to verify if the code is correct and what is the output.</p>
<p>We have created here a table summarizing some of the descriptive statistics for the male respondents in our dataset. Take a look at this table:</p>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Male</th>
<th>Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>N_total</td>
<td>1723</td>
<td>Dataset_CP_m %&gt;% summarize (n=n())</td>
</tr>
<tr class="even">
<td>N_missing</td>
<td>1148</td>
<td>Dataset_CP_m%&gt;% summarize(n_na=sum(is.na(Q37a_HoursWeekChildren)))</td>
</tr>
<tr class="odd">
<td>N_valid</td>
<td>575</td>
<td>Dataset_CP_m%&gt;%summarize(n_valid=sum(!is.na(Q37a_HoursWeekChildren)))</td>
</tr>
<tr class="even">
<td>Mean</td>
<td>16.8591304</td>
<td>Dataset_CP_m%&gt;%summarize(mean = mean(Q37a_HoursWeekChildren, na.rm=T))</td>
</tr>
<tr class="odd">
<td>Median</td>
<td>10</td>
<td>Dataset_CP_m%&gt;%summarize(median = median(Q37a_HoursWeekChildren, na.rm=T))</td>
</tr>
<tr class="even">
<td>Std. Deviation</td>
<td>15.5294252</td>
<td>Dataset_CP_m%&gt;% summarize(sd=sd(Q37a_HoursWeekChildren, na.rm=T))</td>
</tr>
</tbody>
</table>
<p>Notice how we use the pipe operator on the dataset to compute the descriptive statistics with the <em>summarize</em> function and</p>
<ul>
<li><p>the <em>n</em> function to calculate the total number of observations;</p></li>
<li><p>the <em>is.na</em> function to calculate the number of observations with missing values;</p></li>
<li><p>the <em>!</em> operator combined with the <em>is.na</em> function to calculate the opposite of the number of observations with missing values, i.e., the number of observations with valid values;</p></li>
<li><p>the <em>mean</em> function to calculate the mean, with the <em>na.rm</em> option set to TRUE to tell R that there are missing values and it should compute the mean without considering the missing values;</p></li>
<li><p>the <em>median</em> function to calculate the median, with the <em>na.rm</em> option set to TRUE to tell R that there are missing values and it should compute the median without considering the missing values.</p></li>
<li><p>the <em>sd</em> function to calculate the standard deviation, with the <em>na.rm</em> option set to TRUE to tell R that there are missing values and it should compute the standard deviation without considering the missing values.</p></li>
</ul>
<div id="summary-table-using-stargazer" class="section level3 hasAnchor" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> Summary Table using Stargazer<a href="descriptive-statistics.html#summary-table-using-stargazer" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can create a descriptive statistics table for respondents including <strong>mean, median, SD, min, and max</strong>:</p>
<p>We do this by combining <code>psych</code> package with stargazer. We also need to create a data frame since stargazer can’t handle tibbles. <code>out=</code> is so that we can have the tables and we can copy-paste them.</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="descriptive-statistics.html#cb300-1" tabindex="-1"></a>desc <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">describe</span>(Dataset_CP_m <span class="sc">%&gt;%</span></span>
<span id="cb300-2"><a href="descriptive-statistics.html#cb300-2" tabindex="-1"></a>                         <span class="fu">select</span>(Q37a_HoursWeekChildren))</span>
<span id="cb300-3"><a href="descriptive-statistics.html#cb300-3" tabindex="-1"></a></span>
<span id="cb300-4"><a href="descriptive-statistics.html#cb300-4" tabindex="-1"></a><span class="co">#We don&#39;t need all stats</span></span>
<span id="cb300-5"><a href="descriptive-statistics.html#cb300-5" tabindex="-1"></a>desc_table <span class="ot">&lt;-</span> desc <span class="sc">%&gt;%</span></span>
<span id="cb300-6"><a href="descriptive-statistics.html#cb300-6" tabindex="-1"></a>  <span class="fu">select</span>(mean, median, sd, min, max) <span class="sc">%&gt;%</span></span>
<span id="cb300-7"><a href="descriptive-statistics.html#cb300-7" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb300-8"><a href="descriptive-statistics.html#cb300-8" tabindex="-1"></a></span>
<span id="cb300-9"><a href="descriptive-statistics.html#cb300-9" tabindex="-1"></a>desc_table<span class="sc">$</span>Variable <span class="ot">&lt;-</span> <span class="fu">rownames</span>(desc_table)</span>
<span id="cb300-10"><a href="descriptive-statistics.html#cb300-10" tabindex="-1"></a>desc_table <span class="ot">&lt;-</span> desc_table[, <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;median&quot;</span>, <span class="st">&quot;sd&quot;</span>, <span class="st">&quot;min&quot;</span>, <span class="st">&quot;max&quot;</span>)]</span>
<span id="cb300-11"><a href="descriptive-statistics.html#cb300-11" tabindex="-1"></a></span>
<span id="cb300-12"><a href="descriptive-statistics.html#cb300-12" tabindex="-1"></a></span>
<span id="cb300-13"><a href="descriptive-statistics.html#cb300-13" tabindex="-1"></a><span class="fu">stargazer</span>(desc_table, </span>
<span id="cb300-14"><a href="descriptive-statistics.html#cb300-14" tabindex="-1"></a>          <span class="at">type =</span> <span class="st">&quot;text&quot;</span>, </span>
<span id="cb300-15"><a href="descriptive-statistics.html#cb300-15" tabindex="-1"></a>          <span class="at">summary =</span> <span class="cn">FALSE</span>,        <span class="co"># Don&#39;t summarize again</span></span>
<span id="cb300-16"><a href="descriptive-statistics.html#cb300-16" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Descriptive Statistics: Selected Variable (Male Respondents)&quot;</span>,</span>
<span id="cb300-17"><a href="descriptive-statistics.html#cb300-17" tabindex="-1"></a>          <span class="at">out=</span><span class="st">&quot;Desc_Stats_HWC.txt&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Descriptive Statistics: Selected Variable (Male Respondents)
## ===================================================
##                         mean  median   sd   min max
## ---------------------------------------------------
## Q37a_HoursWeekChildren 16.859   10   15.529  1  100
## ---------------------------------------------------</code></pre>
<p>The output would be as a text but you can also save the table to HTML by changing <code>type = "text"</code> to <code>type = "html"</code></p>
</div>
<div id="summary-table-with-grouping-and-stargazer" class="section level3 hasAnchor" number="10.4.2">
<h3><span class="header-section-number">10.4.2</span> Summary Table with Grouping and Stargazer<a href="descriptive-statistics.html#summary-table-with-grouping-and-stargazer" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Say you want to see <code>Q37a_HoursWeekChildren</code> by <code>PaidJob</code>. We use <code>describeBy</code> command which is similar to <code>describe()</code> but it works when you want to group by factor.</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="descriptive-statistics.html#cb302-1" tabindex="-1"></a>desc_grp<span class="ot">&lt;-</span>psych<span class="sc">::</span><span class="fu">describeBy</span>(Dataset_CP_m<span class="sc">$</span>Q37a_HoursWeekChildren, </span>
<span id="cb302-2"><a href="descriptive-statistics.html#cb302-2" tabindex="-1"></a>                  <span class="at">group =</span> Dataset_CP_m<span class="sc">$</span>Q1_PaidJob, </span>
<span id="cb302-3"><a href="descriptive-statistics.html#cb302-3" tabindex="-1"></a>                  <span class="at">mat =</span> <span class="cn">TRUE</span>)  <span class="co"># mat=TRUE gives a nice combined data frame which we use for stargazer</span></span></code></pre></div>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="descriptive-statistics.html#cb303-1" tabindex="-1"></a>df_grp <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(desc_grp)</span>
<span id="cb303-2"><a href="descriptive-statistics.html#cb303-2" tabindex="-1"></a></span>
<span id="cb303-3"><a href="descriptive-statistics.html#cb303-3" tabindex="-1"></a><span class="fu">stargazer</span>(df_grp, <span class="at">type =</span> <span class="st">&quot;text&quot;</span>,</span>
<span id="cb303-4"><a href="descriptive-statistics.html#cb303-4" tabindex="-1"></a>          <span class="at">summary =</span> <span class="cn">FALSE</span>, </span>
<span id="cb303-5"><a href="descriptive-statistics.html#cb303-5" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Hours with Children by Paid Job Status&quot;</span>,</span>
<span id="cb303-6"><a href="descriptive-statistics.html#cb303-6" tabindex="-1"></a>          <span class="at">out=</span><span class="st">&quot;HWCbyPJS.txt&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Hours with Children by Paid Job Status
## ====================================================================================================
##     item   group1   vars  n   mean    sd   median trimmed  mad   min max  range skew  kurtosis  se  
## ----------------------------------------------------------------------------------------------------
## X11  1      Yes      1   189 16.566 17.453   10   13.405  10.378  1  100   99   1.738  3.175   1.269
## X12  2       No      1   14  10.714 10.845 6.500   9.500  6.672   1   35   34   1.063  -0.263  2.898
## X13  3   Don&#39;t Know  1    0                                      Inf -Inf -Inf                      
## X14  4    Refusal    1    1    40            40     40      0    40   40    0                       
## ----------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<div id="control-variables" class="section level2 hasAnchor" number="10.5">
<h2><span class="header-section-number">10.5</span> Control Variables<a href="descriptive-statistics.html#control-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="what-is-a-control-variable" class="section level3 hasAnchor" number="10.5.1">
<h3><span class="header-section-number">10.5.1</span> What is a Control Variable?<a href="descriptive-statistics.html#what-is-a-control-variable" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A <strong>control variable</strong> is a variable that is included in an analysis to account for alternative explanations of a relationship between an explanatory variable and an outcome variable. Control variables are chosen based on theory and prior knowledge.</p>
<p>Suppose we are interested in the relationship between:</p>
<ul>
<li><p>Sex</p></li>
<li><p>Hours spent caring for children per week</p></li>
</ul>
<p>If other characteristics differ systematically between men and women, and those characteristics also affect caregiving time, then differences we observe may not be attributable to sex alone. Control variables helps us isolate the relationship of interest. There are potential control variables we can use but, for now, we use <code>HH1_Num_People</code> due to care tasks may be shared in larger households.</p>
</div>
</div>
<div id="confounding-variables" class="section level2 hasAnchor" number="10.6">
<h2><span class="header-section-number">10.6</span> Confounding Variables<a href="descriptive-statistics.html#confounding-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="what-is-a-confounding-variable" class="section level3 hasAnchor" number="10.6.1">
<h3><span class="header-section-number">10.6.1</span> What is a Confounding Variable?<a href="descriptive-statistics.html#what-is-a-confounding-variable" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A confounder is a variable that is associated with both:</p>
<ol style="list-style-type: decimal">
<li>The explanatory variable and</li>
<li>The outcome variable</li>
</ol>
<p>When a confounder is omitted, the estimated relationship between the explanatory variable and the outcome may be biased or misleading.</p>
<p>In our example,</p>
<ul>
<li><p>Explanatory Variable: Sex</p></li>
<li><p>Outcome variable: Hours caring for children</p></li>
<li><p>Confounder: Hours worked per week (<code>HoursWeekWork</code>)</p></li>
</ul>
<p>We consider <code>HoursWeekWork</code> as a confounder due to meeting both criteria for confounding:</p>
<ol style="list-style-type: decimal">
<li>Men and women differ, on average, in hours worked per week.</li>
<li>Individuals who work more hours typically have less time available for childcare.</li>
</ol>
<p>As a result, observed differences in caregiving time between men and women may partly reflect differences in labor supply rather than caregiving preferences or norms.</p>
<p>Descriptive statistics allow us to detect potential confounding.</p>
</div>
</div>
<div id="difference-between-control-variables-and-confounding-variables" class="section level2 hasAnchor" number="10.7">
<h2><span class="header-section-number">10.7</span> Difference between Control Variables and Confounding Variables<a href="descriptive-statistics.html#difference-between-control-variables-and-confounding-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<table style="width:100%;">
<colgroup>
<col width="23%" />
<col width="22%" />
<col width="31%" />
<col width="22%" />
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th>Variable</th>
<th>What it does / Why we care</th>
<th>Interpretation Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Control variable</strong></td>
<td>HH1_Num_People</td>
<td>Extra factor that only affects the outcome. We include it to be fair.</td>
<td>We check caregiving hours while making sure household size isn’t confusing the result.</td>
</tr>
<tr class="even">
<td><strong>Confounding variable</strong></td>
<td>Q7_HoursWeekWork</td>
<td>A factor that affects both the explanatory and the outcome.</td>
<td>Men and women might work different hours, and the more hours someone works, the less time they have for caregiving.</td>
</tr>
</tbody>
</table>
</div>
<div id="descriptive-statistics-of-control-and-confounding-variables" class="section level2 hasAnchor" number="10.8">
<h2><span class="header-section-number">10.8</span> Descriptive Statistics of Control and Confounding Variables<a href="descriptive-statistics.html#descriptive-statistics-of-control-and-confounding-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For this portion, I will show you the Descriptive Statistics of our outcome, explanatory, control and confounding variables:</p>
<p>a. Create our data frame</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="descriptive-statistics.html#cb305-1" tabindex="-1"></a><span class="co">#Start with males</span></span>
<span id="cb305-2"><a href="descriptive-statistics.html#cb305-2" tabindex="-1"></a>df_m <span class="ot">&lt;-</span> Dataset_CP_m <span class="sc">%&gt;%</span></span>
<span id="cb305-3"><a href="descriptive-statistics.html#cb305-3" tabindex="-1"></a>  <span class="fu">select</span>(Q37a_HoursWeekChildren, HH1_Num_People, Q7_HoursWeekWork) <span class="sc">%&gt;%</span></span>
<span id="cb305-4"><a href="descriptive-statistics.html#cb305-4" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb305-5"><a href="descriptive-statistics.html#cb305-5" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb305-6"><a href="descriptive-statistics.html#cb305-6" tabindex="-1"></a></span>
<span id="cb305-7"><a href="descriptive-statistics.html#cb305-7" tabindex="-1"></a><span class="co"># Females</span></span>
<span id="cb305-8"><a href="descriptive-statistics.html#cb305-8" tabindex="-1"></a>df_f <span class="ot">&lt;-</span> Dataset_CP_f <span class="sc">%&gt;%</span></span>
<span id="cb305-9"><a href="descriptive-statistics.html#cb305-9" tabindex="-1"></a>  <span class="fu">select</span>(Q37a_HoursWeekChildren, HH1_Num_People, Q7_HoursWeekWork) <span class="sc">%&gt;%</span></span>
<span id="cb305-10"><a href="descriptive-statistics.html#cb305-10" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb305-11"><a href="descriptive-statistics.html#cb305-11" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<p>b. use <code>psych::describe</code></p>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="descriptive-statistics.html#cb306-1" tabindex="-1"></a>dsc_male <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">describe</span>(df_m)</span>
<span id="cb306-2"><a href="descriptive-statistics.html#cb306-2" tabindex="-1"></a>dsc_female <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">describe</span>(df_f)</span></code></pre></div>
<p>c. Combine both descriptive statistics results from <code>psych::describe</code></p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="descriptive-statistics.html#cb307-1" tabindex="-1"></a>both_dsc <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb307-2"><a href="descriptive-statistics.html#cb307-2" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">rownames</span>(dsc_male)[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>],</span>
<span id="cb307-3"><a href="descriptive-statistics.html#cb307-3" tabindex="-1"></a>  <span class="at">Mean_Male =</span> dsc_male<span class="sc">$</span>mean[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>],</span>
<span id="cb307-4"><a href="descriptive-statistics.html#cb307-4" tabindex="-1"></a>  <span class="at">Mean_Female =</span> dsc_female<span class="sc">$</span>mean[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>],</span>
<span id="cb307-5"><a href="descriptive-statistics.html#cb307-5" tabindex="-1"></a>  <span class="at">Median_Male =</span> dsc_male<span class="sc">$</span>median[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>],</span>
<span id="cb307-6"><a href="descriptive-statistics.html#cb307-6" tabindex="-1"></a>  <span class="at">Median_Female =</span> dsc_female<span class="sc">$</span>median[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>],</span>
<span id="cb307-7"><a href="descriptive-statistics.html#cb307-7" tabindex="-1"></a>  <span class="at">SD_Male =</span> dsc_male<span class="sc">$</span>sd[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>],</span>
<span id="cb307-8"><a href="descriptive-statistics.html#cb307-8" tabindex="-1"></a>  <span class="at">SD_Female =</span> dsc_female<span class="sc">$</span>sd[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>],</span>
<span id="cb307-9"><a href="descriptive-statistics.html#cb307-9" tabindex="-1"></a>  <span class="at">Min_Male =</span> dsc_male<span class="sc">$</span>min[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>],</span>
<span id="cb307-10"><a href="descriptive-statistics.html#cb307-10" tabindex="-1"></a>  <span class="at">Min_Female =</span> dsc_female<span class="sc">$</span>min[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>],</span>
<span id="cb307-11"><a href="descriptive-statistics.html#cb307-11" tabindex="-1"></a>  <span class="at">Max_Male =</span> dsc_male<span class="sc">$</span>max[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>],</span>
<span id="cb307-12"><a href="descriptive-statistics.html#cb307-12" tabindex="-1"></a>  <span class="at">Max_Female =</span> dsc_female<span class="sc">$</span>max[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb307-13"><a href="descriptive-statistics.html#cb307-13" tabindex="-1"></a>)</span></code></pre></div>
<p>We create a data frame and get the names of the three variables <code>Variable = rownames(dsc_male)[1:3]</code> No need to double this, as it is the same for the female. <code>dsc_male$mean[1:3]</code> gets the mean (median, SD, min, max) for each of the three variables. just copy what was done to the males, for the females.</p>
<p>d. Use <code>stargazer</code> for pretty tables</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="descriptive-statistics.html#cb308-1" tabindex="-1"></a><span class="fu">stargazer</span>(</span>
<span id="cb308-2"><a href="descriptive-statistics.html#cb308-2" tabindex="-1"></a>  both_dsc,</span>
<span id="cb308-3"><a href="descriptive-statistics.html#cb308-3" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">&quot;text&quot;</span>,</span>
<span id="cb308-4"><a href="descriptive-statistics.html#cb308-4" tabindex="-1"></a>  <span class="at">summary =</span> <span class="cn">FALSE</span>,</span>
<span id="cb308-5"><a href="descriptive-statistics.html#cb308-5" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">&quot;Descriptive Statistics: Outcome, Control, and Confounding by Sex&quot;</span>,</span>
<span id="cb308-6"><a href="descriptive-statistics.html#cb308-6" tabindex="-1"></a>  <span class="at">out=</span><span class="st">&quot;DS_OCCbySex.txt&quot;</span></span>
<span id="cb308-7"><a href="descriptive-statistics.html#cb308-7" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## 
## Descriptive Statistics: Outcome, Control, and Confounding by Sex
## ==================================================================================================================================
##          Variable        Mean_Male Mean_Female Median_Male Median_Female SD_Male SD_Female Min_Male Min_Female Max_Male Max_Female
## ----------------------------------------------------------------------------------------------------------------------------------
## 1 Q37a_HoursWeekChildren  17.299     31.748        14           25       14.636   31.349      1         1        100       168    
## 2     HH1_Num_People       3.622      3.265         4            3        1.307    1.147      1         1         9         7     
## 3    Q7_HoursWeekWork     44.414     35.646        40           40       11.186   11.087      8         5         90        80    
## ----------------------------------------------------------------------------------------------------------------------------------</code></pre>
<p>e. <strong>Optional</strong> Use <code>kableExtra</code> for even prettier tables</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="descriptive-statistics.html#cb310-1" tabindex="-1"></a>both_dsc <span class="sc">%&gt;%</span> </span>
<span id="cb310-2"><a href="descriptive-statistics.html#cb310-2" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="st">&quot;html&quot;</span>, <span class="at">escape =</span> <span class="cn">FALSE</span>, <span class="at">align =</span> <span class="st">&quot;c&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb310-3"><a href="descriptive-statistics.html#cb310-3" tabindex="-1"></a>  <span class="fu">add_header_above</span>(<span class="fu">c</span>(<span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">&quot;Mean&quot;</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot;Median&quot;</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot;SD&quot;</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot;Min&quot;</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot;Max&quot;</span> <span class="ot">=</span> <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb310-4"><a href="descriptive-statistics.html#cb310-4" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">position =</span> <span class="st">&quot;center&quot;</span>, <span class="at">font_size =</span> <span class="dv">12</span>, <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hover&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb310-5"><a href="descriptive-statistics.html#cb310-5" tabindex="-1"></a>  <span class="fu">scroll_box</span>(<span class="at">width =</span> <span class="st">&quot;100%&quot;</span>, <span class="at">height =</span> <span class="st">&quot;300px&quot;</span>)</span></code></pre></div>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;position: sticky; top:0; background-color: #FFFFFF;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; position: sticky; top:0; background-color: #FFFFFF;" colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Mean
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; position: sticky; top:0; background-color: #FFFFFF;" colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Median
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; position: sticky; top:0; background-color: #FFFFFF;" colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
SD
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; position: sticky; top:0; background-color: #FFFFFF;" colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Min
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; position: sticky; top:0; background-color: #FFFFFF;" colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Max
</div>
</th>
</tr>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Variable
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Mean_Male
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Mean_Female
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Median_Male
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Median_Female
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
SD_Male
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
SD_Female
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Min_Male
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Min_Female
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Max_Male
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Max_Female
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Q37a_HoursWeekChildren
</td>
<td style="text-align:center;">
17.298630
</td>
<td style="text-align:center;">
31.747826
</td>
<td style="text-align:center;">
14
</td>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
14.635916
</td>
<td style="text-align:center;">
31.34858
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
168
</td>
</tr>
<tr>
<td style="text-align:center;">
HH1_Num_People
</td>
<td style="text-align:center;">
3.621918
</td>
<td style="text-align:center;">
3.265217
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1.307023
</td>
<td style="text-align:center;">
1.14679
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
7
</td>
</tr>
<tr>
<td style="text-align:center;">
Q7_HoursWeekWork
</td>
<td style="text-align:center;">
44.413699
</td>
<td style="text-align:center;">
35.645652
</td>
<td style="text-align:center;">
40
</td>
<td style="text-align:center;">
40
</td>
<td style="text-align:center;">
11.186301
</td>
<td style="text-align:center;">
11.08683
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
90
</td>
<td style="text-align:center;">
80
</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="descriptive-statistics.html#cb311-1" tabindex="-1"></a><span class="co">#saving kableExtra table</span></span>
<span id="cb311-2"><a href="descriptive-statistics.html#cb311-2" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb311-3"><a href="descriptive-statistics.html#cb311-3" tabindex="-1"></a><span class="fu">library</span>(htmltools) <span class="co">#install</span></span>
<span id="cb311-4"><a href="descriptive-statistics.html#cb311-4" tabindex="-1"></a></span>
<span id="cb311-5"><a href="descriptive-statistics.html#cb311-5" tabindex="-1"></a>tbl <span class="ot">&lt;-</span> both_dsc <span class="sc">%&gt;%</span> </span>
<span id="cb311-6"><a href="descriptive-statistics.html#cb311-6" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="st">&quot;html&quot;</span>, <span class="at">escape =</span> <span class="cn">FALSE</span>, <span class="at">align =</span> <span class="st">&quot;c&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb311-7"><a href="descriptive-statistics.html#cb311-7" tabindex="-1"></a>  <span class="fu">add_header_above</span>(<span class="fu">c</span>(<span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">&quot;Mean&quot;</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot;Median&quot;</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot;SD&quot;</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot;Min&quot;</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot;Max&quot;</span> <span class="ot">=</span> <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb311-8"><a href="descriptive-statistics.html#cb311-8" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">position =</span> <span class="st">&quot;center&quot;</span>)</span>
<span id="cb311-9"><a href="descriptive-statistics.html#cb311-9" tabindex="-1"></a></span>
<span id="cb311-10"><a href="descriptive-statistics.html#cb311-10" tabindex="-1"></a></span>
<span id="cb311-11"><a href="descriptive-statistics.html#cb311-11" tabindex="-1"></a><span class="fu">save_html</span>(tbl, <span class="st">&quot;DSOCCbySex.html&quot;</span>)</span></code></pre></div>
<p>For <code>kable("html", escape = FALSE, align = "c")</code> is to have html of the table and the escape is that HTML be shown correctly. The alignment is centered but you can change to “r”, “l”. <code>add_header_above()</code> is to create our multi-column header like the one in the table. The argument where <code>" " = 1</code> is the first column and it is empty but the others span 2 columns because we are differentiating between Male and Female. The table is not stretched across the page but it is centered. You can copy-paste this after rendering your Quarto document. The <code>scroll_box</code> is so that we can scroll when we have a lot of columns.</p>
<div id="results" class="section level4 hasAnchor" number="10.8.0.1">
<h4><span class="header-section-number">10.8.0.1</span> Results:<a href="descriptive-statistics.html#results" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li><p><code>Q37a_HoursWeekChildren</code></p>
<ul>
<li><p>Females spend more time on caregiving than males;</p></li>
<li><p>Women, on average, dedicate around twice as many hours to childcare as men in this sample.</p></li>
</ul></li>
<li><p><code>HH1_Num_People</code> (Control Variable)</p>
<ul>
<li><p>Household size can affect caregiving time but doesn’t vary by sex in a way that confuses results.</p></li>
<li><p>Males have slightly larger households, but the difference is small.</p></li>
<li><p>When comparing caregiving hours between men and women, we account for household size so that differences aren’t simply because one sex lives in larger households.</p></li>
</ul></li>
<li><p><code>HoursWeekWork</code> (Confounding Variable)</p>
<ul>
<li><p>Work hours affect caregiving time and vary by sex.</p></li>
<li><p>Men work slightly more hours per week but the standard deviation show overlap, meaning many men and women work similar hours</p></li>
<li><p>Because work hours affect caregiving and differ by sex, they could confuse the relationship between sex and childcare. Including work hours in the analysis helps isolate the true effect of sex on caregiving.</p></li>
</ul></li>
</ol>
</div>
</div>
<div id="descriptive-statistics-of-categoricalcharacter-variables" class="section level2 hasAnchor" number="10.9">
<h2><span class="header-section-number">10.9</span> Descriptive Statistics of Categorical/Character Variables<a href="descriptive-statistics.html#descriptive-statistics-of-categoricalcharacter-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Some variables such as <code>EmploymentSituation</code> are in character format. Therefore, to find out more about the variable, we use <code>gtsummary</code> . You can transform these variables to numeric, though, this is also a good way to know how many respondents there are.</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="descriptive-statistics.html#cb312-1" tabindex="-1"></a>Dataset_CP_m <span class="sc">%&gt;%</span></span>
<span id="cb312-2"><a href="descriptive-statistics.html#cb312-2" tabindex="-1"></a>  <span class="fu">select</span>(HH2d_EmploymentSituation) <span class="sc">%&gt;%</span></span>
<span id="cb312-3"><a href="descriptive-statistics.html#cb312-3" tabindex="-1"></a>  <span class="fu">tbl_summary</span>()</span></code></pre></div>
<div id="zmaxvdmuzw" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#zmaxvdmuzw table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#zmaxvdmuzw thead, #zmaxvdmuzw tbody, #zmaxvdmuzw tfoot, #zmaxvdmuzw tr, #zmaxvdmuzw td, #zmaxvdmuzw th {
  border-style: none;
}

#zmaxvdmuzw p {
  margin: 0;
  padding: 0;
}

#zmaxvdmuzw .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#zmaxvdmuzw .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#zmaxvdmuzw .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#zmaxvdmuzw .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#zmaxvdmuzw .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zmaxvdmuzw .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zmaxvdmuzw .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zmaxvdmuzw .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#zmaxvdmuzw .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#zmaxvdmuzw .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#zmaxvdmuzw .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#zmaxvdmuzw .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#zmaxvdmuzw .gt_spanner_row {
  border-bottom-style: hidden;
}

#zmaxvdmuzw .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#zmaxvdmuzw .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#zmaxvdmuzw .gt_from_md > :first-child {
  margin-top: 0;
}

#zmaxvdmuzw .gt_from_md > :last-child {
  margin-bottom: 0;
}

#zmaxvdmuzw .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#zmaxvdmuzw .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#zmaxvdmuzw .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#zmaxvdmuzw .gt_row_group_first td {
  border-top-width: 2px;
}

#zmaxvdmuzw .gt_row_group_first th {
  border-top-width: 2px;
}

#zmaxvdmuzw .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zmaxvdmuzw .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#zmaxvdmuzw .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#zmaxvdmuzw .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zmaxvdmuzw .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zmaxvdmuzw .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#zmaxvdmuzw .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#zmaxvdmuzw .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#zmaxvdmuzw .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zmaxvdmuzw .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zmaxvdmuzw .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#zmaxvdmuzw .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zmaxvdmuzw .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#zmaxvdmuzw .gt_left {
  text-align: left;
}

#zmaxvdmuzw .gt_center {
  text-align: center;
}

#zmaxvdmuzw .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#zmaxvdmuzw .gt_font_normal {
  font-weight: normal;
}

#zmaxvdmuzw .gt_font_bold {
  font-weight: bold;
}

#zmaxvdmuzw .gt_font_italic {
  font-style: italic;
}

#zmaxvdmuzw .gt_super {
  font-size: 65%;
}

#zmaxvdmuzw .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#zmaxvdmuzw .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#zmaxvdmuzw .gt_indent_1 {
  text-indent: 5px;
}

#zmaxvdmuzw .gt_indent_2 {
  text-indent: 10px;
}

#zmaxvdmuzw .gt_indent_3 {
  text-indent: 15px;
}

#zmaxvdmuzw .gt_indent_4 {
  text-indent: 20px;
}

#zmaxvdmuzw .gt_indent_5 {
  text-indent: 25px;
}

#zmaxvdmuzw .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#zmaxvdmuzw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="label"><span class='gt_from_md'><strong>Characteristic</strong></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="stat_0"><span class='gt_from_md'><strong>N = 1,723</strong></span><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">HH2d_EmploymentSituation</td>
<td headers="stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    At work as employee or employer/self-employed</td>
<td headers="stat_0" class="gt_row gt_center">870 (50%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Employed, on child-care leave or other leave</td>
<td headers="stat_0" class="gt_row gt_center">6 (0.3%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    At work as relative assisting on family farm or business</td>
<td headers="stat_0" class="gt_row gt_center">13 (0.8%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unemployed less than 12 months</td>
<td headers="stat_0" class="gt_row gt_center">66 (3.8%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unemployed 12 months or more</td>
<td headers="stat_0" class="gt_row gt_center">90 (5.2%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unable to work due to long-term illness or disability</td>
<td headers="stat_0" class="gt_row gt_center">46 (2.7%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Retired</td>
<td headers="stat_0" class="gt_row gt_center">520 (30%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Full time homemaker/ responsible for ordinary shopping and looking after the home</td>
<td headers="stat_0" class="gt_row gt_center">5 (0.3%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    In education (at school, university, etc.) / student</td>
<td headers="stat_0" class="gt_row gt_center">90 (5.2%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Other</td>
<td headers="stat_0" class="gt_row gt_center">17 (1.0%)</td></tr>
  </tbody>
  <tfoot>
    <tr class="gt_footnotes">
      <td class="gt_footnote" colspan="2"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> <span class='gt_from_md'>n (%)</span></td>
    </tr>
  </tfoot>
</table>
</div>
</div>
<div id="importance-of-descriptive-statistics" class="section level2 hasAnchor" number="10.10">
<h2><span class="header-section-number">10.10</span> Importance of Descriptive Statistics:<a href="descriptive-statistics.html#importance-of-descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Descriptive statistics serve as tools to summarize and organize data into meaningful insights, making it easier to understand and communicate findings. The following are the key aspects of descriptive statistics:</p>
<div id="definition" class="section level4 hasAnchor" number="10.10.0.1">
<h4><span class="header-section-number">10.10.0.1</span> <strong>Definition</strong><a href="descriptive-statistics.html#definition" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Descriptive statistics involve summarizing, organizing, and simplifying data in a way that is understandable and interpretable. This can include numerical summaries, tables, and graphical representations to describe the distribution, central tendency, and variability of data.</p>
</div>
<div id="key-components-of-descriptive-statistics" class="section level3 hasAnchor" number="10.10.1">
<h3><span class="header-section-number">10.10.1</span> <strong>Key Components of Descriptive Statistics</strong><a href="descriptive-statistics.html#key-components-of-descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p><strong>Measures of Central Tendency</strong>:</p>
<ul>
<li><p><strong>Mean</strong>: The average value, useful for symmetric distributions without outliers.</p></li>
<li><p><strong>Median</strong>: The middle value in the data, efficient even with skewness and outliers.</p></li>
<li><p><strong>Mode</strong>: The most frequent value, helpful for categorical or multimodal distributions.</p></li>
</ul></li>
<li><p><strong>Measures of Variability</strong>:</p>
<ul>
<li><strong>Range:</strong> Difference between the largest and smallest values. Shows how wide the data can go.</li>
<li><strong>Standard Deviation (SD):</strong> Shows how close most values are to the average. A small SD → most numbers are similar; a large SD → numbers vary a lot.</li>
<li><strong>Interquartile Range (IQR):</strong> Shows the spread of the middle 50% of the data. Focuses on the “typical” range, ignoring extreme values.</li>
<li><strong>Standard Error (SE):</strong> Shows how precise the mean estimate is; smaller SE → mean is more reliable.</li>
</ul></li>
<li><p><strong>Shape of the Data</strong></p>
<ul>
<li><p><strong>Skewness</strong>: Measures asymmetry. Positive –&gt; long right tail; Negative –&gt; long left tail</p></li>
<li><p><strong>Kurtosis:</strong> Measures heaviness of tails. High –&gt; more outliers; low –&gt; flatter distribution</p></li>
</ul></li>
<li><p><strong>Data Distribution</strong>:</p>
<ul>
<li>Histograms and frequency distributions help identify the shape (e.g., symmetric, skewed, bimodal) and any potential outliers in the dataset.</li>
</ul></li>
<li><p><strong>Data Representation</strong>:</p>
<ul>
<li>Graphical methods like bar charts, line graphs, pie charts, and boxplots make patterns and trends in the data more visible and easier to interpret.</li>
</ul></li>
</ol>
</div>
<div id="when-to-use-mean-or-median" class="section level3 hasAnchor" number="10.10.2">
<h3><span class="header-section-number">10.10.2</span> <strong>When to Use Mean or Median</strong><a href="descriptive-statistics.html#when-to-use-mean-or-median" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>The mean is preferred when the data is symmetrically distributed without extreme values.</p></li>
<li><p>The median is better for skewed distributions or datasets with significant outliers, as it is not affected by extreme values.</p></li>
<li><p>Example: In income data, where a few individuals earn significantly more than the majority, the median provides a more realistic “typical” income.</p></li>
</ul>
</div>
<div id="how-descriptive-statistics-help-in-regression" class="section level3 hasAnchor" number="10.10.3">
<h3><span class="header-section-number">10.10.3</span> How Descriptive Statistics Help in Regression<a href="descriptive-statistics.html#how-descriptive-statistics-help-in-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p>Choosing Variables to Include:</p>
<p>By looking at descriptive stats, we can see which variables affect our outcome and which might mix up relationships.</p>
<ul>
<li><p><strong>Control variables</strong> are factors that only affect the outcome.</p>
<p>Example: Household size might affect caregiving hours but is not our main focus.</p></li>
<li><p><strong>Confounding variables</strong> affect both the explanatory variable and the outcome.</p>
<p>Example: Hours worked per week can differ by sex and affect caregiving, so we need to account for it.</p></li>
</ul></li>
<li><p>Preparing for Regression</p>
<ul>
<li><p>Descriptive stats let us check for outliers, skewed data, or missing values before modeling.</p></li>
<li><p>They help us understand the scale of variables and whether transformations might be needed.</p></li>
<li><p>They show if control and confounding variables need special attention in our regression models.</p></li>
</ul></li>
</ol>
<blockquote>
<p>Takeaway: Descriptive statistics are the first step in regression analysis.</p>
</blockquote>
</div>
<div id="limitations" class="section level3 hasAnchor" number="10.10.4">
<h3><span class="header-section-number">10.10.4</span> <strong>Limitations</strong><a href="descriptive-statistics.html#limitations" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Descriptive statistics only describe the data at hand; they do not infer or predict trends in the population.</p></li>
<li><p>Without considering measures of variability (e.g., SD or IQR), central tendency measures (mean, median) can be misleading.</p></li>
<li><p>They cannot fully reveal causal relationships; confounding can still bias conclusions if not properly addressed.</p></li>
</ul>
</div>
</div>
<div id="closing-4" class="section level2 hasAnchor" number="10.11">
<h2><span class="header-section-number">10.11</span> Closing<a href="descriptive-statistics.html#closing-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>Do <strong>NOT</strong> clean your Environment</p>
<ul>
<li>You will use the datasets for your quiz.</li>
</ul></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="advanced-visualizations.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["LBOMETR_Course_Book.pdf", "LBOMETR_Course_Book.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "depth": 4
  }
});
});
</script>

</body>

</html>
